modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java

Following the guidance here: http://stackoverflow.com/questions/724043/http-url-address-encoding-in-java
Addressing issue #31

URL path encoding

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParserExtension.java

SwaggerCompatConverter method is not implemented yet.

PR for swagger-api/swagger-parser#39

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java

Fixes #51: Accept header has been fixed.

Fixes #51: Accept header has been fixed.

---

README.md

This is just a simple MD update.

updated compat parser with instructions for swagger 1.2 to 2

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/LegacyConverterTest.java
modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/singleFile.json

Fixed #60: Handling of operations with no responses has been fixed.

Fixed #60: Handling of operations with no responses has been fixed.

---

pom.xml

to address jackson 2.4.x upgrade

updated swagger-core version

---

README.md

update the Readme file with latest maven versions

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java

Hi
We've just started using Swagger to define a set of commerce API (contract first) and were having a lot of trouble with nested in line references.
This update patch seems to work for us. Let me know if you need anything else as I couldn't find much info on how to contribute.
thanks
Ross

Nested References

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java

To fix https://github.com/swagger-api/swagger-codegen/issues/1382

Fix "required" attribute during deserialization

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

Add test case for https://github.com/swagger-api/swagger-parser/pull/110

Add test case for parameter's required

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java

Ensure default values are retained on parameters

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/consumes_and_produces

- removed duplicated null check
- added support for empty consumes and produces at operation level
- added 4 test cases for consumes and produces

Add support for empty consumes and produces at operation level

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java

This looks like an error - probably copy'n'paste gone wrong.

Fix discriminator.

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java

try to fix #120 .
Please tell me if there are some existing tests, and I will update tests later.

handle `BasicAuthorization` in `SwaggerCompatConverter`

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
pom.xml

Resolves #143, requires https://github.com/swagger-api/swagger-core/commit/6d1f14f58e881544e15ac435712067c9b198ad14 to be published via 1.5.5 release

added additionalProperties parsing

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

updated property type

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java
modules/swagger-parser/src/test/java/io/swagger/parser/Swagger20ParserTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
modules/swagger-parser/src/test/resources/thing.json
pom.xml

added tests for composed models

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

added test, discriminator field to expected fields

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

fixed typo

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

Add vendor extensions to ComposedModel

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

Fix for #167

---

modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/PathUtils.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
modules/swagger-parser/src/test/resources/s p a c e s/uber.json

@fehguy
References #152 and #125, updating Paths.get calls in case of file scheme in URL, supporting absolute urls with file scheme. 
It doesn't implement a comprehensive solution for location/URI management but it basically stays on safe side converting backslashes and using URI.create().
Build tested on Windows.

refs #152 #125 - handle 'file' URL scheme

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/LegacyConverterTest.java
modules/swagger-parser/pom.xml
pom.xml

Added basePath

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/transform/migrate/V11AllowableValuesMigrator.java

allows returning if an unexpected allowableValues type is found

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-parser/pom.xml
modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ParameterProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ResponseProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/ClasspathHelper.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/JsonToYamlFileDuplicator.java
modules/swagger-parser/src/test/java/io/swagger/parser/processors/DefinitionsProcessorTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/processors/ResponseProcessorTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/DeserializationUtilsTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/PathUtilTest.java

formatting, added logger

---

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerResolver.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java
modules/swagger-parser/src/test/java/io/swagger/parser/RelativeReferenceTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/ResolverCacheTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerResolverTest.java

Added support for relative refs

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/OperationProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/ResponseResolverTest.java

check for vendor extensions in response deserialization

---

modules/swagger-parser/src/test/java/io/swagger/parser/ResponseResolverTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

Tests to inspect inner property in array response

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

Check for null child, set object properties

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

Added test for empty schema properties

---

pom.xml

set version for maven compiler plugin

Fix warning during maven build

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

added minLength, maxLength

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

vendor extension tests, fixes

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/objectExample.json

fixed example of type array

---

modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

This was requested by @fehguy in https://github.com/swagger-api/swagger-parser/issues/263

Adds failing test for issue 263

---

modules/swagger-parser/src/main/java/io/swagger/parser/AbstractParser.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

The continuation of pull request #252.

parseContents returns friendly error messages.

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

This is for https://github.com/swagger-api/swagger-parser/issues/268

Adds failing test for issue 268

---

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/file-reference-with-vendor-ext/a.yaml
modules/swagger-parser/src/test/resources/file-reference-with-vendor-ext/b.yaml

This is for https://github.com/swagger-api/swagger-parser/issues/274

Adds failing test for issue #274

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/nested-references/a.yaml
modules/swagger-parser/src/test/resources/nested-references/b.yaml

This is for https://github.com/swagger-api/swagger-parser/issues/270

Fixes issue 270

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
modules/swagger-parser/src/test/resources/issue_277.yaml

Tests for #277

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

This is for https://github.com/swagger-api/swagger-parser/issues/271

Fixes issue 271

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/file-reference-to-recursive-defs/a.yaml
modules/swagger-parser/src/test/resources/file-reference-to-recursive-defs/b.yaml

This is for https://github.com/swagger-api/swagger-parser/issues/278

Adds failing test for issue278

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerResolverTest.java

change to use internal parser logic instead of Json mapper

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue_286.yaml
modules/swagger-parser/src/test/resources/issue_286_Allergy.yaml
modules/swagger-parser/src/test/resources/issue_286_Pet.yaml
modules/swagger-parser/src/test/resources/issue_286_PetList.yaml

tests for #286

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/issue-308.yaml
modules/swagger-parser/src/test/resources/nested-file-references/paging.yaml

added tests for #308

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/common/paging.yaml
modules/swagger-parser/src/test/resources/nested-file-references/issue-310.yaml

added tests for #310

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/events.yaml
modules/swagger-parser/src/test/resources/nested-file-references/issue-312.yaml

added tests for chained references

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/common/common2/bar.yaml
modules/swagger-parser/src/test/resources/nested-file-references/common/pagingWithFolderRef.yaml
modules/swagger-parser/src/test/resources/nested-file-references/eventsCase9.yaml
modules/swagger-parser/src/test/resources/nested-file-references/issue-323.yaml

added files, tests to verify #323

---

modules/swagger-parser/src/test/java/io/swagger/parser/NetworkReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/common/common2/issue-328-bar.yaml
modules/swagger-parser/src/test/resources/nested-file-references/common/issue-328-paging.yaml
modules/swagger-parser/src/test/resources/nested-file-references/issue-328-events.yaml
modules/swagger-parser/src/test/resources/nested-file-references/issue-328.yaml

tests for #328

---

modules/swagger-parser/src/test/java/io/swagger/parser/NetworkReferenceTests.java
modules/swagger-parser/src/test/resources/nested-network-references/common/issue-330-entities.yaml
modules/swagger-parser/src/test/resources/nested-network-references/common/issue-330-paging.yaml
modules/swagger-parser/src/test/resources/nested-network-references/common/issue-330-users.yaml
modules/swagger-parser/src/test/resources/nested-network-references/issue-330.yaml

added tests for multi-server relative references

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/issue-289-b.yaml
modules/swagger-parser/src/test/resources/issue-289.yaml

tests for #289

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/PropertyProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/NetworkReferenceTests.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/nested-file-references/issue-335-bar.json
modules/swagger-parser/src/test/resources/nested-file-references/issue-335.json
pom.xml

Address remote references before resolving

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/nested-file-references/issue-304.json
modules/swagger-parser/src/test/resources/nested-file-references/issue-304_child.json
modules/swagger-parser/src/test/resources/nested-file-references/issue-304_parent.json

Tests for relative refs

---

README.md

Pull request for [Issue 347](https://github.com/swagger-api/swagger-parser/issues/347)

Maven central badge

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/RemoteUrlTest.java

added cleaning of url

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/LegacyConverterTest.java
modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/issue-104.json

added enum support

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/io/HttpClient.java
modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java

added debugs

---

modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

Test for allOf with single element

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

added missing properties, tests

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
modules/swagger-parser/src/test/resources/issue-1261.yaml

Depends on swagger-api/swagger-core#2046

Include example from inlined response schemas.

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/petstore-codegen.yaml

added tests

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue_360.yaml

Fixes #360 
This moves the deserialization of body parameters out of jackson to allow for error messages and proper handling of extensions

Deserialize body param manually

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue_360.yaml

This is a test case for issue #360, as requested in https://github.com/swagger-api/swagger-parser/issues/360#issuecomment-270528101.

Test case for x-examples in body parameter (#360)

---

modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java
modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java

expose SSL error as message

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue_360.yaml

added assertions

---

modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

Check ugly enums

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue-339.json

Don't convert minimum, maximum to double

---

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/NetworkReferenceTests.java
modules/swagger-parser/src/test/java/io/swagger/parser/RelativeReferenceTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/nested-network-references/issue-411-remote2.yaml
modules/swagger-parser/src/test/resources/nested-network-references/issue-411-server.yaml

better handling of remote references

---

modules/swagger-parser/src/test/java/io/swagger/parser/AnchorTest.java

Anchor test

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ParameterProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
pom.xml

catch invalid cast

---

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java

Fixes #432: null pointer access in SwaggerParser

Fixes #432: null pointer access in SwaggerParser

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

Capture extenstion tags for array models

---

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/test/java/io/swagger/parser/LocalReferenceTests.java
modules/swagger-parser/src/test/resources/nested-network-references/issue-454-components.yaml
modules/swagger-parser/src/test/resources/nested-network-references/issue-454.yaml

added handling for relative ref rooting

---

.travis.yml
appveyor.yml
modules/swagger-parser-core/src/main/java/io/swagger/parser/models/SwaggerParseResult.java
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v2-converter/src/main/java/io/swagger/parser/v2/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-455.json
modules/swagger-parser-v2-converter/src/test/resources/petstore.yaml
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
pom.xml

fixed responses, updated to rc1 models

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/OpenAPIV3Parser.java

added version check

---

.gitignore
README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerResolverTest.java
modules/swagger-parser/src/test/resources/relative-file-references/yaml/issue-5753-definitions.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/issue-5753.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/conflict.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/error.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/example.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/foo.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/health.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/localrefence.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/pet.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/models/reflex.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/parameters/params.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/parent.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/paths/healthPath.yaml
modules/swagger-parser/src/test/resources/relative-file-references/yaml/responses/errorResponses.yaml
pom.xml

updated versions

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/CallbackProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/HeaderProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/LinkProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/ParameterProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/RequestBodyProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/ResponseProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenApiResolverTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java
modules/swagger-parser-v3/src/test/resources/oas3.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/remote_callback.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/remote_example.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/remote_link.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/remote_parameter.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/requestBody.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/responses_notFound.yaml

Additional Remote tests for the OpenApiResolver Feature/3.0.0 rc2
Remote Parameter
Remote Response
Remote Request Body
Remote Callback
Remote Link
Remote Example

Additional Remote tests for the OpenApiResolver Feature/3.0.0 rc2

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/DeserializationUtils.java

Issue found by running custom written query on lgtm.com (as discussed by email with @fehguy: https://lgtm.com/query/2023830455/project:24760076/lang:java/

parser change.

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/allOf-example/allOf.json

Fix referenced models parsing on definitions

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIV3ParserTest.java

Added method read, to used it in the readme file.

adding shell methods and test

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java

Fixed example string in the schema.

Fixing example in schema and test

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/SchemaTypeUtil.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java

refactor method creatSchemaByType

refactor method creatSchemaByType

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java
modules/swagger-parser-v3/src/test/resources/oas3.yaml.template

Fix #510 
Required parameters depend on the type of security

Fixing securityScheme parsing

---

modules/swagger-parser/pom.xml
pom.xml

* updated jackson version
* clean up poms

deps versions

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java

Fix examples

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java

The schema's enum it's now being saved as the correct type of the elements of the list.

fixing deserializing of enum in schema

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/parser/v2/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-17.json
modules/swagger-parser-v2-converter/src/test/resources/issue-25.json
modules/swagger-parser-v2-converter/src/test/resources/issue-32.json
modules/swagger-parser-v2-converter/src/test/resources/issue-36.json

This issue was fixed in this PR:
https://github.com/swagger-api/swagger-spec-converter/issues/36

Issue-36 fixed!

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/parser/v2/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java

Issue 32 Fixed: https://github.com/swagger-api/swagger-spec-converter/issues/32

Issue 32 Fixed

---

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java

adding a isValid method in ParserResult

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/parser/v2/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-33.json
modules/swagger-parser-v2-converter/src/test/resources/issue-35.json

Fixed: https://github.com/swagger-api/swagger-spec-converter/issues/35

Issue-35 Fixed

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/parser/v2/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-34.json

Issue 15 Fixed.
Test added.
The Contact Extension in v2 is missing. TODO comment added.

Issue-15 Test added, Some fixes in Responses, Paths, Items extensions

---

modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-19.json

Issue 33 Tested

---

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

Method added to decide when to resolve references in parser.

Resolve References Options in Parser

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/singleFile.json
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

refs swagger-api/swagger-core#2507 - fix compat-spec-parser and array test

refs swagger-api/swagger-core#2507 - fix compat-spec-parser and array test

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-599.json

Issue fixed. 
Options and Head Operations added.

Issue 599 solved

---

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java

fixing the internal refs paths - resolving refs #608

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
modules/swagger-parser-v3/src/test/resources/oas.yaml

fixing parsing of empty securityRequirement - refs #492

---

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/allOf-relative-file-references/definitions.yaml
modules/swagger-parser/src/test/resources/allOf-relative-file-references/swagger.yaml

adding test allOf relative files - issue#604

adding test allOf relative files - issue#604

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/definitions.yaml
modules/swagger-parser/src/test/resources/refEnum.yaml

adding tests to support #622 #623

testing #622 #623

---

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java
modules/swagger-parser/src/test/resources/Pet.yaml
modules/swagger-parser/src/test/resources/main.yaml

adding test for issue #421 
refs swagger-api/swagger-codegen#5663

adding test for issue #421

---

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/RelativeReferenceTest.java

RelativeReferenceTest fixed test 213.

fix NPE in remote paths refs test213

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
modules/swagger-compat-spec-parser/src/test/java/io/swagger/parserExtensions/SwaggerCompatConverterTest.java
modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/issue-641.json

This PR addresses the regression issue #641.

fixing issue#641 added test

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/Person.json
modules/swagger-parser/src/test/resources/Persons.json
modules/swagger-parser/src/test/resources/issue_642.yaml
modules/swagger-parser/src/test/resources/issue_657/issue_657.json

Fixing Relative ref was being treated as an URL - issue #657

---

modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/OperationConverterTest.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ResponseProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerResolverTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/processors/ResponseProcessorTest.java

Testing response schema changes issue #567

Adding support to schema Property as Model in Response Object  issue #567

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-662.yaml

Fixes #662 for OpenAPI 3.0 support.

issue-662: fix NPE in converter with empty paths

---

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
modules/swagger-parser-v3/src/test/resources/joel.yaml

fixing test selfReferenced Spec

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ParameterProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue-684.json

fixing issue #684 - added test and solution to avoid NPE

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/odin.yaml
modules/swagger-parser-v3/src/test/resources/resources/urn_jsonschema_com_issinc_odin_display_CreatePlan.json

Adding test for issue #682 - ClassPath 

---

modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-672.json

Depends on Swagger-core Master Solution.
First merge the solution: https://github.com/swagger-api/swagger-core/pull/2753
Then merge the tests.

refs #672 - NullPointerException when converting an spec (Tests) 

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java

changes in additional properties external process

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java

This PR closes https://github.com/swagger-api/swagger-parser/issues/710

Fix missing SwaggerParseResult.message

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java

Hi team,
This PR is to solve the null pointer exception in swagger converter as mentioned in the issue #732
Thanks,
Mohammed

NPE in SwaggerConverter (Issue 732)

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-755.yaml

Fixes issue described here: OpenAPITools/openapi-generator#177

Do not read Info block if it does not exist

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-756.json

Hi team,
This PR is to solve the issue 'OpenAPI v2 converter: NullPointerException when schema field is missing in body parameter' as mentioned in #756 
Thanks,
Mohammed

Fix for issue 756

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/RemoteUrlTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue768-main.yaml
modules/swagger-parser/src/test/resources/issue768-reference.yaml

Hi team,
This PR is to solve the issue '$ref in external file in requestBody with resolve option true' as mentioned in #768 
Thanks,
Mohammed

Fix for issue 768 ($ref in external file in requestBody with resolve option true)

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java

Hi team,
This PR is to solve the issue 'ResolveFully does not resolve the request body reference' as mentioned in [https://github.com/swagger-api/swagger-parser/issues/664](url)
Thanks,
Mohammed

Fix for issue 664

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release 1.0.37

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release 2.0.2

---

modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue799.json
pom.xml

Test for Issue #799 oas3 depends on https://github.com/swagger-api/swagger-parser/pull/801

Test for Issue #799 oas3

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/ExternalRefProcessorTest.java
modules/swagger-parser-v3/src/test/resources/relative-with-url/relative-with-local.yaml
modules/swagger-parser-v3/src/test/resources/relative-with-url/relative-with-url.yaml

This patch fixes https://github.com/swagger-api/swagger-parser/issues/805.

fix relative ref with http ref bug

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java

Added try-catch block in case of a NPE to allow process to continue.

Fix NPE issue 813 OAS 3

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-820.yaml

Convert x-nullable for formData parameter

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/OperationProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ResponseProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/OperationProcessorTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
modules/swagger-parser-v3/src/test/resources/oapi-reference-test/components/referent.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test/components/response-with-reference.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test/components/schema-with-reference.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test/index.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test2/components/referent.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test2/components/schema-with-reference.yaml
modules/swagger-parser-v3/src/test/resources/oapi-reference-test2/index.yaml
modules/swagger-parser-v3/src/test/resources/relative-file-references/json/paths/healthPath.json
modules/swagger-parser-v3/src/test/resources/relative-file-references/json/responses/errorResponses.json
modules/swagger-parser-v3/src/test/resources/relative-file-references/yaml/paths/healthPath.yaml
modules/swagger-parser-v3/src/test/resources/relative-file-references/yaml/responses/errorResponses.yaml

Fix issue #811 OAS3 - RefResponse -> RefSchema external Resolving

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v1.0.38

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 2.0.5-SNAPSHOT

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-834/components/response1.yaml
modules/swagger-parser-v3/src/test/resources/issue-834/components/response2.yaml
modules/swagger-parser-v3/src/test/resources/issue-834/components/schema.yaml
modules/swagger-parser-v3/src/test/resources/issue-834/index.yaml
modules/swagger-parser/src/test/resources/Issue-783/issue-783-b.yaml
modules/swagger-parser/src/test/resources/Issue-783/issue-783.yaml

fixes to issue #834 in OAS 3

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java

Hi team,
This PR is to solve the issue #835 (OAS Conversion of formData reference parameters to request body is incorrect (OAS 2 to 3 conversion))
Thanks,
Mohammed

Fix for issue 835

---

README.md

Since issuestats.com seems to stay offline we should use shields as it's the best alternative afaik.

Update Readme to use badges from Shields.io

---

README.md

Remove windows stats from readme file

Remove windows stats from readme file

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/reusableParametersWithExternalRef.json

Hi team,
This PR is to solve the issue #844 (parser not honoring redirect responses in swagger 2.0)
Thanks,
Mohammed

Fix for issue 844

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ComponentsProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/exampleSpecs/specs/common/confirmMessageType_v01.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/common/confirmMessageType_v02.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/common/dateType_v01.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/common/linkType_v01.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/common/simpleIDType_v01.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/my-domain/test-api/v1/schemas/test-api-schema_v01.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/my-domain/test-api/v1/schemas/test-api-schema_v02.json
modules/swagger-parser/src/test/resources/exampleSpecs/specs/my-domain/test-api/v1/test-api-swagger_v1.json
modules/swagger-parser/src/test/resources/specs2/common/confirmMessageType_v01.json
modules/swagger-parser/src/test/resources/specs2/common/dateType_v01.json
modules/swagger-parser/src/test/resources/specs2/common/linkType_v01.json
modules/swagger-parser/src/test/resources/specs2/common/simpleIDType_v01.json
modules/swagger-parser/src/test/resources/specs2/my-domain/test-api/v1/schemas/test-api-schema_v01.json
modules/swagger-parser/src/test/resources/specs2/my-domain/test-api/v1/test-api-swagger_v1.json

fix issue relative ref array property items

fix issue relative ref array property items

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue_855.yaml

Hi team,
This PR is to solve the issue #855 (Request Body Internal Ref Not Resolved)
Thanks,
Mohammed

Fix for issue 855

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue-435/main.yaml
modules/swagger-parser/src/test/resources/issue-435/sub.yaml
modules/swagger-parser/src/test/resources/nested-references/b.yaml
modules/swagger-parser/src/test/resources/nested-references/c.yaml
modules/swagger-parser/src/test/resources/subsub.yaml

Fixes for issue #435 and #434 because the original PRs are stale

---

README.md

Reverts swagger-api/swagger-parser#866

Revert "prepare switch to v1 branch"

---

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java

Hi team,
This PR is to solve the issue #872 (Remove NPE logs by checking the null).
Thanks,
Mohammed

Fix for issue 872

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/duplicateOperationId.json

Hi team,
This PR is to solve the issue #258 (issue warning on duplicate operation ids)
Thanks,
Mohammed

Fix for issue 258

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue_879.yaml

Hi team,
This PR is to solve the issue #878 (Callback with $ref is not working).
Thanks,
Mohammed

Fix for issue 878

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue_877.yaml

Hi team,
This PR is to solve the issue #877 (Parameter Internal Ref Not Resolved).
Thanks,
Mohammed

Fix for issue 877

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

pull request is created for the change

change packaging to (OSGi) bundle

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

Reverts swagger-api/swagger-parser#428

Revert "change packaging to (OSGi) bundle"

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/apiWithMultipleTags.json

added fix for issue 889

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue892-main.yaml

Hi Team,
This PR is to solve the issue #892  (Warn message is missing when the path key doesn't start with slash).
Thanks,
Sailesh V

Fix for issue 892

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/RemoteUrlTest.java

Hi team,
This PR is to solve the issue #898 (Swagger parser failed to parse the input swagger url with space).
Thanks,

Fix for issue 898

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/RemoteUrlTest.java

Hi team,
This PR is to solve the issue #898 (Swagger parser failed to parse the input swagger url with space) in open api parser.
Thanks,

Code roll-in for issue 898

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/main/java/io/swagger/parser/processors/ModelProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue-901/ref.yaml
modules/swagger-parser/src/test/resources/issue-901/ref2.yaml
modules/swagger-parser/src/test/resources/issue-901/spec.yaml
modules/swagger-parser/src/test/resources/issue-901/spec2.yaml

Issue 901 v1.039

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue_918.yaml

Hi team,
This PR is to solve the issue #918 (Headers Internal Ref Not Resolved).
Thanks,

Fix for issue 918

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/models/RefType.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-901/ref.yaml
modules/swagger-parser-v3/src/test/resources/issue-901/ref2.yaml
modules/swagger-parser-v3/src/test/resources/issue-901/spec.yaml
modules/swagger-parser-v3/src/test/resources/issue-901/spec2.yaml
modules/swagger-parser-v3/src/test/resources/issue-913/BO/Common/BasicComponents.json
modules/swagger-parser-v3/src/test/resources/issue-913/BO/Resource/ApiSpecificationBO.json
modules/swagger-parser-v3/src/test/resources/issue-913/BS/ApiSpecification.yaml
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java

Issues 901 - 913 to oas3

---

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/sample/SwaggerPetstore.yaml

Hi team,
This test indicates that the issue mentioned in #941 is not reproduced.
Thanks,
Mohammed

Test added for issue 941

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue_884.yaml

Hi team,
This PR is to solve the issue #936 (Headers in link is not considered in resolve fully)
Thanks,

Fix for issue 936

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/Issue_931.json

Pull request for Issue Fix #931

Fixed Issue 931

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OAIDeserializationTest.java
modules/swagger-parser-v3/src/test/resources/issue_911.yaml
modules/swagger-parser/src/test/resources/duplicateOperationId.json

Hi team,
This PR is to solve the issue #911 (Not able to identify the missed path variables).
Thanks,

Fix for issue 911

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
modules/swagger-parser/src/test/resources/duplicateOperationId.json
modules/swagger-parser/src/test/resources/issue_911.yaml

Hi team,
This PR is to solve the issue #911 (Not able to identify the missed path variables) in swagger parser v1
Thanks,

Fix for issue 911 in swagger parser v1

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
modules/swagger-parser-v3/src/test/resources/simple.yaml

Regression issue 943

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/parameter-conversion.json

To fix https://github.com/swagger-api/swagger-parser/issues/968

Fix missing top level extensions in OAS v2 spec

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/API-Service-2.0.0-swagger.yaml
modules/swagger-parser/src/test/resources/Domain1.yaml
modules/swagger-parser/src/test/resources/Domain2.yaml

ref #901 - fixes property references with dot in name

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/PropertyProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/SimpleAPI.yaml
modules/swagger-parser/src/test/resources/SimpleDomain.yaml
modules/swagger-parser/src/test/resources/allOf-property-relative-file-references/child.yaml
modules/swagger-parser/src/test/resources/allOf-property-relative-file-references/parent.yaml
modules/swagger-parser/src/test/resources/nested-external-response-references/sub-folder/common-responses.yaml

ref #901 - fixes references with dot in property name

ref #901 - fixes references with dot in property name

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/SchemaTypeUtil.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/integerDefault.yaml
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue-901/CDK-Global-Int/Domain-Service/2.0.0.yaml

Set correct integer value #973

fixes issue #973

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ReferenceValidator.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue-934.yaml

Hi Team,
This PR is to solve the issue #934 (Open API parser is not validating the invalid references).
Thanks,
Sailesh V

Fix for #934

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ParameterProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/Issue_948.json

Fixed Issue_948

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.43-SNAPSHOT

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java

fix for default integer #1029 #1015

fix for default integer #1029 #1015

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/RefUtilsTest.java

PR for issue #1035 
1. Trim ".." from root as well
2. If rel starts with "/", trim root to domain
This is my first PR on this project - I'd be happy to receive feedback. Thanks!

PR for Issue #1035

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-1032.yaml

fixes #1032 (and https://github.com/swagger-api/swagger-codegen/issues/8874)

Refine creation of Schema to fix #1032

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release 1.0.44

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
modules/swagger-parser-v3/src/test/resources/issue_1039.yaml

fixed set types to schemas 

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1063/openapi.yaml
modules/swagger-parser-v3/src/test/resources/issue-1063/references.oas3.yaml

fix for Parameter Validation Issue 

---

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerResolver.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/relative-file-references/json/parent.json
modules/swagger-parser/src/test/resources/relative-file-references/yaml/parent.yaml

swagger-api/swagger-parser#1087

Ensure top level parameter relative references are resolved

---

README.md

Readme Update v1 - Security Section Added

Readme Update v1 - Security Section Added

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/resolve-fully-map.yaml

See Issue for details.
https://github.com/swagger-api/swagger-parser/issues/1125

Fix for fully resoling map schema.

---

README.md

Adding badges to display jenkins build status for java 8 and java 9 on master branch.

Add Jenkins Build Status Badges

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ParameterProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/ParameterProcessorTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1078/api.yaml
modules/swagger-parser-v3/src/test/resources/issue-1078/common.yaml

Adds support for content vs schema when describing more complex parameter definitions

Issue #1078

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
modules/swagger-parser-v3/src/test/resources/issue-1157/allOf-example.yaml
modules/swagger-parser-v3/src/test/resources/issue-1157/anyOf-example.yaml
modules/swagger-parser-v3/src/test/resources/issue-1157/oneOf-example.yaml

Modified ResolverFully to replace old Schema with $ref with new aggregated Schema in schemas Map

Issue #1157 - AllOf references not resolved by parser, OneOf and AnyOf resolved correctly

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue1169.yaml

Fix for multiple path params in a same URI segment of a path

---

pom.xml

update pom slf4j in v3 refs #1167

update pom slf4j in v3

---

pom.xml

update pom slf4j in v1 refs #1175

update pom slf4j in v1

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/FileReferenceTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue1148.yaml

fix for setFlatten with Schema containing dot produces invalid ref

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIResolver.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ComponentsProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1147/common.yaml
modules/swagger-parser-v3/src/test/resources/issue-1147/issue1147.yaml

Fix for issue Reference not correctly rewritten with setResolve #1147

fix for issue Reference not correctly rewritten with setResolve #1147

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v1.0.46

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v2.0.14

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 2.0.15-SNAPSHOT

---

pom.xml

bump parser v1 version

---

pom.xml

bump core v1 version

---

pom.xml

bump core v2 in parser v3

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java

Reverts swagger-api/swagger-parser#1197

Revert "Issue#1196 Fix OpenAPIV3Parser.readContents() encoding error"

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/AuthorizationValue.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/RemoteUrlTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java

I don't want to pass my authorization tokens to any host.
Hence I added the possibility to limit the authorization to a list of urls.

allow to filter authorization by URL

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java

Send PR (https://github.com/swagger-api/swagger-parser/pull/1197) again

Resend "Issue#1196 Fix OpenAPIV3Parser.readContents() encoding error"

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java
modules/swagger-parser-v3/src/test/resources/flatten.json

Issue 1200

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java

Fixed https://github.com/swagger-api/swagger-parser/issues/1202

Fixed getting null scopes issue

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/OperationProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/callbacks-issue/domain.yaml
modules/swagger-parser-v3/src/test/resources/callbacks-issue/swagger.yaml

refs - issue #1215 callback with $ref not being resolved

callback with $ref not being resolved

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/CallbackProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java

fixing callback reference resolving code

fixing callback reference resolving code

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/codegen-issue-9773/domain.yaml
modules/swagger-parser-v3/src/test/resources/codegen-issue-9773/openapi.yaml
modules/swagger-parser-v3/src/test/resources/issue-1081/spec2.yaml
modules/swagger-parser-v3/src/test/resources/remote_references/remote_requestBody.yaml

refs - swagger-api/swagger-codegen#9773 - fixing remote schema ref resolving in referenced request body

fixing remote schema ref resolving in referenced request body

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

Prepare release v.1047

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v2.0.15 master branch - depends on https://github.com/swagger-api/swagger-parser/pull/1219

Prepare release v2.0.15 master branch

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.48 snapshot

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 2.0.16-snapshot

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java
modules/swagger-parser-v3/src/test/resources/codegen-issue-8601.yaml

refs swagger-api/swagger-codegen#8601 - flatten composed models in body schema

refs swagger-api/swagger-codegen#8601 - flatten composed models in body schema

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/codegen-remote-responses/Responses/1.0.0/domain.yaml
modules/swagger-parser-v3/src/test/resources/codegen-remote-responses/openapi.yaml
modules/swagger-parser-v3/src/test/resources/relative-issue/api.yaml
modules/swagger-parser-v3/src/test/resources/relative-issue/subfolder/domain.yaml

test and fix for #1246 
Resolve relative issue in response with a referenced schema

Resolve relative issue

---

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

updating tests

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue-1143.json

refs - issue #1143 - changes in converter to support properties in ComposedModel
depends on:
- https://github.com/swagger-api/swagger-core/pull/3342
- https://github.com/swagger-api/swagger-parser/pull/1240

refs - issue #1143 - changes in converter to support properties in Composed Model

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.49-snapshot

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump-snapshot-2.0.17

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java

#1267 - fix ArrayModel parsing to handle "uniqueItems" flag

---

modules/swagger-parser-v3/pom.xml

This will improve the logging output for unit tests.

add [slf4j-simple] to swagger-parser-v3/pom.xml

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release 1.0.49

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release 2.0.17

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.50 snaphot

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

pushing snapshot 2.0.18

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java

Issue: https://github.com/swagger-api/swagger-parser/issues/1274

Inside a content, include the mediaType in the location string.

---

pom.xml

notes:
https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.13.md

JUnit 4.13

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
modules/swagger-parser/src/test/resources/issue-1249.json

Swagger 2 validation allows path params to be non-required

Fix for issue #1249

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1309.yaml

Issue #1309 - Applying regular expression only to objects under components

Applying regular expression only to objects under components

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare-release-1.0.50

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare-release-2.0.18

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.51 snapshot

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump snapshot 2.0.19

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1319.yaml
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java

Path parameter required value must be true

Fix for issue 1319

---

pom.xml

bump core version 1.6.1

---

pom.xml

bump core version 2.1.2

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare-release-v2.0.19

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump snapshot v2.0.20

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/folder/domains/Test/api.test.com/v2.yaml
modules/swagger-parser/src/test/resources/swagger-reference-response.yaml

Changes to implemente resolving of Reference response with a nested reference schema

Reference response schema

---

pom.xml

update parser v2 1.0.51-snapshot

update parser v2 1.0.51-snapshot

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-1359.yaml

fixes #1359 
@gracekarina, please help me taking a look on this and let me know if i'm not making a mess here :/
This PR is needed to fix issue [swagger-codegen#8704](https://github.com/swagger-api/swagger-codegen/issues/8704) on codegen

apply flatten option for converted definitions

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-505/pets/def.yml
modules/swagger-parser-v3/src/test/resources/issue-505/pets/pets.yml
modules/swagger-parser-v3/src/test/resources/issue-505/petstore.yml

Fix Unable to load RELATIVE ref for parameters, examples and links.
@gracekarina
Link: #505

gh-505: Fix relative paths in parameters, examples and links

---

README.md
modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v1.0.51

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v2.0.20

---

modules/swagger-compat-spec-parser/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump 1.0.52-SNAPSHOT

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump-2.0.21-snapshot

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/SwaggerParseResult.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/exception/EncodingNotSupportedException.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/exception/ReadContentException.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java

Improvement for issue #1303 

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/SwaggerParseResult.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/exception/EncodingNotSupportedException.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/exception/ReadContentException.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java

Refactor OpenAPIV3Parser to make it more clear
Fixes #1303

Improvement for issue #1303

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/exampleFlag.yaml
pom.xml

related PRs and tickets:
* https://github.com/swagger-api/swagger-core/pull/3637
* https://github.com/swagger-api/swagger-inflector/issues/371

process exampleSetFlag to flag deserialization of null example vs missing

---

README.md
modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

prepare release v2.0.21

---

modules/swagger-parser-core/pom.xml
modules/swagger-parser-v2-converter/pom.xml
modules/swagger-parser-v3/pom.xml
modules/swagger-parser/pom.xml
pom.xml

bump snapshot v 2.0.22-SNAPSHOT

bump snapshot v 2.0.22-SNAPSHOT

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue1398.yaml

fix for MultipleOf with negative value issue #1398

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue_1433-resolve-schema-without-type.yaml

fix ResolverFully for schema without type

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

Avoid to resolve openAPI if it is null
Fixes #1455

fix NPE when parsing V2 with OpenAPIV3Parser and resolveFully option

---

pom.xml

update junit deps

---

pom.xml

update junit version in master

update junit version

---

README.md

We've moved from jenkins to github actions and we need to update the badges to show the status of the workflow for the master branch in github action.

Update Badges for Master Branch

---

README.md

Changing badges from jenkins to github actions

Updated badged for v1 builds

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1419.yaml

Fix for issue-1419.
The issue here is that when enum field is having an array value, It is getting logged as error.
This was fixed as the missing condition was handled. The value is currently saved as string.

Fix for issue-1419

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/nested-references-2/main.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-2/schemas/greeting-message.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-2/schemas/greeting-response.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-2/schemas/shared-defs.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-3/greeting-message.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-3/greeting-response.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-3/main.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-3/shared-defs.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-4/main.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-4/schemas/shared-defs.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-4/schemas/sub/greeting-message.yaml
modules/swagger-parser-v3/src/test/resources/nested-references-4/schemas/sub/greeting-response.yaml

In this pull request we have fix for nested references for external references within subfolder.

fixed bug related to nested definitions within subfolder

---

modules/swagger-compat-spec-parser/pom.xml

Replace fge-dependencies with their java-json-tools replacements

---

pom.xml

bump v1 parser in master branch

bump v1 parser in master branch

---

README.md

Change in project from Java 7 to Java 8 was made: https://github.com/swagger-api/swagger-parser/pull/1463/

docs: Update Readme to specify Java 8 requirement

---

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/arrayItemsResolving/ArrayDomain.yaml
modules/swagger-parser/src/test/resources/arrayItemsResolving/Swagger.yaml

Resolving array items references into Definitions

resolving array items references into Definitions

---

pom.xml

bump deps version

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ParameterProcessor.java

This PR does the following:
* Removing an unreachable branch with a duplicated condition. The block inside is the same as covered above.

refactor: remove repeated else-if

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1540/a.json

Hello,bro.It seems that the content of extensions under the node is not parsed here,resulting in the extensions content of all nodes not being parsed,so here is added to take the extensions node and parse the content under the node.

Fix the problem that the content of extensions cannot be parsed

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/PathsProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/RelativeReferenceTest.java
modules/swagger-parser-v3/src/test/resources/relative-references-example/_responses/UnexpectedError.yaml
modules/swagger-parser-v3/src/test/resources/relative-references-example/_schemas/error.yaml
modules/swagger-parser-v3/src/test/resources/relative-references-example/openapi.yaml
modules/swagger-parser-v3/src/test/resources/relative-references-example/security/_resources/authorize.yaml
modules/swagger-parser-v3/src/test/resources/relative-references-example/security/_resources/login.yaml
modules/swagger-parser-v3/src/test/resources/relative-references-example/security/_schemas/usernamepasswordcredentials.yaml

This PR includes a fix & testcase for this [issue] (https://github.com/swagger-api/swagger-parser/issues/1459)

fix handling of relative references

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ComponentsProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/ComponentsProcessorTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/example0/api.json
modules/swagger-parser-v3/src/test/resources/example0/config.json
modules/swagger-parser-v3/src/test/resources/example0/models/combination.json
modules/swagger-parser-v3/src/test/resources/example0/models/combinations.json
modules/swagger-parser-v3/src/test/resources/example0/models/common/error.json
modules/swagger-parser-v3/src/test/resources/example0/models/common/link.json
modules/swagger-parser-v3/src/test/resources/issue-1518/api.json
modules/swagger-parser-v3/src/test/resources/issue-1518/models/analemmata.json
modules/swagger-parser-v3/src/test/resources/issue-1518/models/common/essot.json
modules/swagger-parser-v3/src/test/resources/issue-1518/models/common/stunts.json
modules/swagger-parser-v3/src/test/resources/issue-1518/models/common/tashotSipe.json

Fix for #1518 
This PR addresses the duplicated schemas resolution that comes from differents urls, but are equals in their content.

Fix for 1518 with no SOF

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java

Fixed #1579, Resolve callbacks when ResolveFully flag is set to true.

Fixed #1579 - Resolve callbacks when ResolveFully is true

---

README.md

Minor change to fix the package for SwaggerParserExtension in the README.

Fix SwaggerParserExtension package in README

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
modules/swagger-parser/src/test/resources/relativeTest.yaml

fix for redirect issue #1417

---

modules/swagger-compat-spec-parser/pom.xml

Update httpclient dependency from 4.5.2 to 4.5.13 refs #1604

Update httpclient dependency

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/OperationProcessor.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ResponseProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1561/exceptions.yml
modules/swagger-parser-v3/src/test/resources/issue-1561/swagger.yaml

Fix and Issue 1561:
Add resolved responses to components section in main spec

Fix and Issue 1561: Add resolved responses to components section in main spec

---

.github/workflows/maven-pulls.yml
.github/workflows/maven-v1-pulls.yml
.github/workflows/maven-v1.yml
.github/workflows/maven.yml
.github/workflows/next-snapshot-v1.yml
.github/workflows/next-snapshot.yml
.github/workflows/prepare-release-v1.yml
.github/workflows/prepare-release.yml
.github/workflows/release-v1.yml
.github/workflows/release.yml

Reference:
https://github.com/actions/setup-java

chore: setup-java v1 to v2

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
modules/swagger-parser/src/test/resources/issue1608.json

Hi team,
This PR is to solve issue #1608 (V2 setResolveFully does not work)
Thanks,

Fix for issue 1608

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java

fix https://github.com/swagger-api/swagger-parser/issues/1638

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

Refs #1644 
Improves AllowEmptyString option validation for field "In" in parameters deserialization.

improves AllowEmptyString option validation

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
pom.xml

this PR add support for items in all Schema types in OpenAPI 2.0 #1636 
depends on: https://github.com/swagger-api/swagger-core/pull/4109

fix for #1636

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/ParseOptions.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OAI31DeserializationTest.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/3.1.0/basic.yaml
modules/swagger-parser-v3/src/test/resources/3.1.0/schemaSiblings.yaml
modules/swagger-parser-v3/src/test/resources/3.1.0/test/basicOAS30.yaml
modules/swagger-parser-v3/src/test/resources/3.1.0/test/basicOAS31.yaml

References tickets 405 and 405

Implementation of JSONSchema deserialization in oas 3.1 support 

---

README.md

Correct spelling mistake #1667 in readme

Correct spelling mistake in readme

---

pom.xml

Signed-off-by: Pratim S Chaudhuri <pratim.sunilkumar.chaudhuri@mercer.com>
This fix includes changes to mitigate CVE reported at - https://github.com/FasterXML/jackson-databind/issues/3328

Update Jackson to include CVE fixed in version 2.12.6

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1658/api2.yaml
modules/swagger-parser-v3/src/test/resources/issue-1658/apis.yaml
modules/swagger-parser-v3/src/test/resources/issue-1658/issue1658.yaml

fix and test for issue#1658
fix exception while file do not have '/'

fix exception while file do not have '/'

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue-1266/issue-1266-resolved.yaml
modules/swagger-parser-v3/src/test/resources/issue-1266/issue-1266.yaml

This small fix resolve the issue #1266 and add a test for the issue resolved

Fix the issue of not merging the extensions in allOf

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OAI31DeserializationTest.java

fix array test
remove print lines

Adding keys to set

---

pom.xml

update v1 parser in pom

---

pom.xml

Update snapshot 1.5.9

---

pom.xml

Update v1 parser snapshot 1.5.9

Update v1 parser snapshot 1.5.9

---

modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
pom.xml

improve test for issue #1685 get messages from conversion v2 to v3

improve test for issue #1685 get messages from conversion v2 to v3

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/ParseOptions.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

Parser does not validate an undefined ref property
refs #1643

Fix and test for issue 1643 - Parser does not validate an undefined ref property

---

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/ParseOptions.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

set validate internal ref option to true by default

set validate internal ref option to true by default

---

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
modules/swagger-parser/src/test/resources/issue1169-noSplit.yaml

This contains a fix for path-element fixing (Delegated PR for @lucian-r)
fix for v3 is in #1718

fix for issue 1169 that works without explicit separators

---

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
modules/swagger-parser-v2-converter/src/test/resources/issue-1715.yaml

[swagger-parser-v2-converter] vendor extensions from body params not copied to RequestBody

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/issue1637.yaml

fix for issue#1637
Fix for invalid location of style and explode when content is present

Fix for invalid location of style and explode when content is present

---

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java

improve test for issue1637

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java
modules/swagger-parser-v3/src/test/resources/unexpectedNullValues.yaml

fix for issue unexpected Null Examples when flatten set to true.

fix for issue unexpectedNullExamples when flatten set to true

---

LICENSE
NOTICE
pom.xml

Changes in license and notice

---

modules/swagger-parser-v3/pom.xml

refs #1753 - revert to test scope for slf4j-simple dep

---

modules/swagger-parser-cli/pom.xml

Adding plugin to identify main Class

Adding plugin to identify main Class

---

.github/actions/action.yml
.github/workflows/validate-workflow.yml

Changes to use last Snapshot in validate Action

Changes to use last Snapshot in validate Action

---

modules/swagger-parser-cli/src/main/java/io/swagger/v3/parser/SwaggerParser.java

Refactor and changing parameter type

Refactor and changing parameter type

---

modules/swagger-parser-cli/src/main/java/io/swagger/v3/parser/SwaggerParser.java

improve boolean arguments

---

.github/actions/action.yml
.github/workflows/validate-workflow.yml

use latest snapshot

---

.github/actions/action.yml

url enhancement

---

.github/actions/action.yml

use release version in action

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java
modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/OperationProcessor.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
modules/swagger-parser-v3/src/test/resources/parametersAsNumbers/domain.yaml
modules/swagger-parser-v3/src/test/resources/parametersAsNumbers/swagger.yaml

Allow deferencing External Parameters and External responses as numbers

Allow deferencing External Parameters and External responses as numbers

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java
modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java

It fixes only one of the failing cases of the provided tests though.
I didn't consider cases where the default value is defined on the enum and expected to be inherited by the property.

Issue 1454

---

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ClasspathHelper.java

Reverts swagger-api/swagger-parser#1969

Revert "Add fallback to Thread Context Class Loader for resource loading"
