swagger-api/swagger-parser

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java
Fix issue that "void" response is treated as model when converting spec from v1.2 to v2.0.
See more at swagger-api/swagger-codegen#305
=> Fix issue that "void" response is treated as model

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java
Accepting UTF-8 characters to fix problems for accents.
For example, the Portuguese word **Não** was reading like **nÃ£o**.
After this PR, the word is **Não** as expected.
=> Accepting UTF-8 characters

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerResolver.java, modules/swagger-parser/src/test/scala/SwaggerResolverTest.scala, pom.xml
=> added yaml support in resolver

modules/swagger-parser/src/main/java/io/swagger/parser/util/ClasspathHelper.java
I gave my new classpath loading a whirl when deployed in Tomcat and the ClasspathHelper did not find the swagger.json in WEB-INF/classes inside my war. 
After some googling I ran across this [this](http://stackoverflow.com/questions/7615040/difference-between-classloader-getsystemresourceasstream-and-getclass-getresou) stack overflow article. Where they describe that in a web app world the classloader situation is more complicated.
So my solution is to change the code try looking for the resource in two places.
=> When loading from the classpath look in more than one place

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/PathUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/PathUtilTest.java
When I refactored SwaggerResolver I didn't test the following use case:
```java
new SwaggerParser().read("swagger.yaml");
```
The parsing works just fine but the parent directory was not being computed correctly. This causes problems when you try and reference another file via
```yaml
$ref: ./anotherFile.yaml
```
The resolving code would get a NPE when it tried to resolve the ref.
The fix is to take "swagger.yaml" get the absolute path and then get the parent directory.
=> Parent directory fix

pom.xml
Analogously to [Pull Request #1161 of swagger-codegen](https://github.com/swagger-api/swagger-codegen/pull/1161), this fixes the build on OpenJDK on Linux.
Compared to [Issue #1160 there](https://github.com/swagger-api/swagger-codegen/issues/1160), here the problem shows by different error messages (because here we use JUnit and not TestNG, I guess).
I see once this:
```
java.lang.IllegalStateException: To run on OpenJDK 64-Bit Server VM use -javaagent:/home/paulo/.m2/repository/org/jmockit/jmockit/1.18/jmockit-1.18.jar
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.maven.surefire.common.junit4.JUnit4Reflector.createRequest(JUnit4Reflector.java:63)
at …
```
=> Update JMockit to 1.19.

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
The parser was incorrectly mapping a BasicAuthentication SecurityScheme to ApiAuthentication. For instance with this fix proper java client is generated with support for Basic Auth:
`client/src/main/java/com/example/service/ApiClient.java`:
```java
public ApiClient() {
// Use ISO 8601 format for date and datetime.
// See https://en.wikipedia.org/wiki/ISO_8601
this.dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
// Use UTC as the default time zone.
this.dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
// Set default User-Agent.
setUserAgent("Java-Swagger");
// Setup authentications (key: authentication name, value: authentication).
authentications = new HashMap<String, Authentication>();
authentications.put("hallo", new HttpBasicAuth());
// Prevent the authentications …
```
=> Use BasicAuthDefinition for basic securityScheme

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
Addresses #122 
Updated SwaggerDeserializer so that a RefResponse is returned when a $ref attribute is present in the Response json.
This follows a similar approach to what is currently implemented for Parameter and RefParameter.
=> SwaggerDeserializer support for RefResponse

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java
Looks like there was another issue in my commit - if the spec being processed had an internal ref it ended up generating a null pointer exception when processRefToExternalDefinition() was recursively called as the Model was null when pulled from the cache.
Added a check to make sure it's an external ref before processing. This does lead to a situation in which some definitions are left unprocessed
=> Another Null Pointer

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/test/java/io/swagger/parser/ResolverCacheTest.java
This fixes #137 by updating the ResolverCache pattern matching to allow names with spaces and introduces additional unit tests to test the lookup.
=> Update ResolverCache for names with spaces

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java, modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/LegacyConverterTest.java
This fixes #139.  It modifies conversion logic so that void response types will still result in a default response being created when converting to swagger 2.0.  Previously void response types would result in no responses attribute for the given operation and an invalid swagger 2.0.
=> Transform "void" response types

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
Now verifying that values are of the correct type.  This doesn't do strict checking but ensures that a `ValueNode` is not a container type, etc.
Fixes #158
=> Type checking

modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
@fehguy 
Alternative approach for #169, possibly limited to the specific or similar issue (call to https://api.rocrooster.net/api-docs.json with server checking user agent) without adding deps; 
adds User-Agent header to RemoteUrl connection
tested with https://api.rocrooster.net/api-docs.json in https://github.com/frantuma/swagger-parser/commit/a4a1e8bb3dea8493a1fcaacaf2d97b590f13a08b, test removed because hitting external URL
=> Refs #169 - User agent in URLConnection used by Swagger20Parser.

modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java, modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/DeserializationUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/DeserializationUtilsTest.java, modules/swagger-parser/src/test/resources/issue_146.yaml
@fehguy refs #146, also related to https://github.com/swagger-api/swagger-codegen/issues/1662 and https://github.com/swagger-api/swagger-editor/issues/609
This solution introduces "direct" usage of snakeyaml, which handles correctly scenarios as in #146  example.
It updates YAML "data as string" reading, replacing jackson-dataformat-yaml custom streaming solution with a snakeyaml load of Object, then converted/read by Jackson into JSON, probably at the expenses of performance.
=> Refs #146 - Yaml anchor refs parsing. Direct usage of snakeyaml

modules/swagger-parser/src/main/java/io/swagger/parser/util/HostAuthorizationValue.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/ManagedValue.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/HostAuthorizationValueTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RemoteUrlTest.java, pom.xml
The `io.swagger.parser.util.RemoteUrl` changes default SSL settings as follows:
- default socket factory is configured to trust any certificates
- default host name validator is configured to validate any hosts
So, projects which use our parser implicitly get insecure SSL configuration.
This PR eliminates this flaw but preserve the ability to turn on 'trust all' configuration for parser connections only via the `-Dio.swagger.parser.util.RemoteUrl.trastAll=true` system property.
The second issue relates to inability to control sending of authorization values to remote hosts. When we parse a specification which references remote locations and provide a set of `AuthorizationValue` instances these values will be send to all those locations regardless of the fact whether a remote host requires …
=> A couple of security improvements

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
Currently the following snippet is parsed as invalid with message "attribute definitions.CssColor.properties is missing".
```yaml
definitions:
CssColor:
pattern: ^#[0-9A-F]{6}$
type: string
```
The `properties` attribute is not relevant for schemas that are not of `type: object`, and even for object schemas, the [JSON schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor64) states that it can be missing and the default value is empty object.
This PR removes the requirement for the `properties` attribute.
=> Don't require properties attribute on schema definitions

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
Please review/accept this pull request to fix Issue #204. The fix is required by swagger-codegen Issue [#2258](https://github.com/swagger-api/swagger-codegen/issues/2258), for which I shall shortly be raising a PR. Many thanks.
=> Fix, test for #204 "allOf deserialised incorrectly"

.gitignore, modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
#222 
VendorExtensions in SecurityDefinitions are not being deserialized.
Added serialization for vendor extensions to SecuritySchemeDefinition
=> add vendor extension to SecurityDefinitions

modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java, modules/swagger-parser/src/test/resources/issue250.json
SwaggerDeserializationResult now contains the errors generated by jackson if json parsing fails.
There is a disabled test that considers the case when the spec is provide as a string. I'll add a different commit that will change the api of AbstractParser.stringToNode (will throw a Jackson related exception).
=> Generate better error messages

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
=> Don't configure the parent with allOf

modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RefUtilsTest.java
I've noticed that external files referenced by $ref are loaded without specifying character encoding. Because of that, diacritics are parsed incorrectly. This should fix it.
Note that `IOUtils.toString(InputStream input)` is deprecated in the latest version of commons-io in favor of `IOUtils.toString(InputStream, Charset)`
=> Read external reference file with UTF-8 encoding

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
When `type` is not explicit, we can infer the type of a property based on enum values.
This fixes #263
=> Infer type from enum in properties

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/test/java/io/swagger/parser/ResolverCacheTest.java
=> Unescape JSON Pointer segments using the algorithm described in RFC 6901, section 5

modules/swagger-parser/pom.xml, modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/nested-file-references/book.yaml, modules/swagger-parser/src/test/resources/nested-file-references/components/entities.yaml, modules/swagger-parser/src/test/resources/nested-file-references/issue-306.yaml
=> Fix issue with relative file references

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/nested-file-references/common2/bar.yaml, modules/swagger-parser/src/test/resources/nested-file-references/eventsWithItems.yaml, modules/swagger-parser/src/test/resources/nested-file-references/issue-314.yaml
=> Ensure multiple referenced folders resolve

modules/swagger-parser/src/main/java/io/swagger/parser/processors/DefinitionsProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RefUtilsTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java, modules/swagger-parser/src/test/resources/nested-file-references/common/paging2.yaml, modules/swagger-parser/src/test/resources/nested-file-references/eventsWithPaging.yaml, modules/swagger-parser/src/test/resources/nested-file-references/issue-316.yaml
Fixes #316, #319, #147
Replaces #298
=> fix for root traversals

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/DefinitionsProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java
Fixes #278 
@diegode this is to fix the issue in #278 but...
I don't necessarily agree with the expectations in a couple tests.  Once I fixed this bug some other test failures appeared.
For example, when we have this:
```yaml
definitions:
x:
properties:
foo:
$ref: '#/definitions/y'
y:
$ref: '#/definitions/z'
z:
type: object
```
That the parser should change the definitions to this:
```yaml
definitions:
x:
properties:
foo:
$ref: '#/definitions/z'
z:
type: object
```
Because a model is referencing `y` in this example as a property, there may be intent and _value_ in retaining that name.  So even though `y` absorbs all the properties of `z`, the name `y` may be useful.
So this PR changes the behavior of a couple tests that were previously behaving differently.  Since you put them there, I …
=> added check to avoid removing referenced models #278

modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-336-currency_code.json, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-336-error.json, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-336-error_details.json, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-336-link_description.json, modules/swagger-parser/src/test/resources/nested-file-references/issue-336.json, modules/swagger-parser/src/test/resources/nested-file-references/title/issue-336-copy.json, modules/swagger-parser/src/test/resources/nested-file-references/title/issue-336-datatypes.json, modules/swagger-parser/src/test/resources/nested-file-references/title/issue-336-reservation.json, modules/swagger-parser/src/test/resources/nested-file-references/title/issue-336-title.json
=> added tests for file references

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/nested-file-references/issue-340-Bar.json, modules/swagger-parser/src/test/resources/nested-file-references/issue-340.json
There are cases where there are model name collisions.  There are scenarios where there is a clear priority when this happens, and a model implementation should clobber a model reference
Fixes #340
=> handle model collisions

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
[JSON Schema v4 allows enum to contain values of any type, explicitly including null](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.20).  Swagger v2.0 adopts this definition without change (as far as I am aware) but the parser previously parsed any non-string values as `null`.  This PR fixes this to return the string representation of non-string primitive values and to warn about unsupported non-primitive values and add test cases to cover these.
For reference, I discovered this issue when attempting to run swagger-codegen against a Swagger declaration with an integer enumeration, which produced the following error:
Exception in thread "main" java.lang.RuntimeException: Could not process model 'MyEnum'.Please make sure that your schema is correct!
at …
=> Fix parsing of non-string enum values

modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/PathUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
The URLs produced by `java.io.File.toURI()` (and deprecated `.toURL()`) and `java.lang.Class.getResource(String)` contain no additional slashes between `file:` and the path.  This makes using `Swagger20Parser` with files from these methods a bit more painful than it needs to be.  This PR addresses this by recognizing strings starting with `file:` as file URLs and adds tests to cover this case.
I hope you find it useful,
Kevin
=> Support file URL scheme produced by java.io.File et al.

appveyor.yml
This PR is a follow-up to https://github.com/swagger-api/swagger-parser/pull/374#issuecomment-269657834 which adds the `appveyor.yml` file which I used for CI testing on Windows.  It simply runs the relevant Maven goals for Java 7 and 8.  An example of the output is at https://ci.appveyor.com/project/kevinoid/swagger-parser/build/1.0.9
To setup CI for this repository, you will need to create a free AppVeyor account and add this repository as an AppVeyor project.  The process is described in [the docs](https://www.appveyor.com/docs/) and should take less than 5 minutes.
Thanks!
Kevin
=> Add configuration for AppVeyor CI

README.md
Hyperlink was not linked to anything before. It should link to https://letsencrypt.org
=> Add hyperlink to Let's Encrypt

modules/swagger-compat-spec-parser/pom.xml
Updating httpclient to 4.5.2 to mitigate CVE-2014-3577 & CVE-2015-5262.  v4.5.2 is not the latest version but chosen for popularity.
=> httpclient to 4.5.2 to mitigate CVE threats

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
=> Added extension parsing test

modules/swagger-parser/src/test/resources/petstore.json
This fixes a validation error of petstore.json against the OpenAPI specification 2.0. petstore.json will pass a validation against the OpenAPI specification 2.0.
=> Example specification petstore.json is not compliant with the OpenAPI specification 2.0

modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue_357.yaml
Test case includes a path with two path parameters: pathParam1 and pathParam2.
A GET operation overrides pathParam1, and due to the reported bug, fails to inherit pathParam2.
With the fix, the test passes.
=> Issue 357 - Test and Fix

modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue_358.yaml
I've supplied a test that demonstrates the problem described by the
issue.
When the swagger model is parsed, the GET operation ends up with two identical parameters, because the override test in `PathsProcessor` was performed before the path parameter was resolved, causing the parameter not to match the operation parameter.
=> Issue 358 Path param matching fails

modules/swagger-compat-spec-parser/pom.xml
Update json-schema-validator from 2.2.3 to 2.2.8 (with change in groupId to reflect ownership change).   Addresses Cross Site Scripting vulnerability from libphonenumber dependency.
=> Update json-schema-validator (SONATYPE-2015-0090)

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java, modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/BodyParameterConverterTest.java
Fixes https://github.com/swagger-api/swagger-codegen/issues/1241
=> primitive schemas are no longer lost in conversion

modules/swagger-parser-v3/pom.xml, modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/processors/HeaderProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/oas.yaml, modules/swagger-parser-v3/src/test/resources/oas2.yaml.template, modules/swagger-parser-v3/src/test/resources/oas3.yaml.template, modules/swagger-parser-v3/src/test/resources/oas4.yaml, pom.xml
The Example attribute now supports primitives (integer, big decimal, string), objects and arrays, where the spec says the value can be Any. 
Please Merge [[https://github.com/swagger-api/swagger-core/pull/2406]](https://github.com/swagger-api/swagger-core/pull/2406) before merging this.
=> Fix example implementation on schema, header, parameter and media Type

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/composed.yaml
The deserializing of composedSchema was only returning the last object of the arrays, and there were some issues in the resolving of this schemas.
=> Fixing composedSchema deserializing and resolving, allof, anyOf, Oneof

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java
Fix #514 
added a test for each composedSchema
=> #514 fixing composed schema parsing

modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
`Json.pretty(openAPI)` makes the extensions go under its own `extension` node. This results that when parsing it again they will be gone.
The variable `prettyJson` in my testcase has the value 
```json
{
"openapi" : "3.0.0",
"servers" : [ {
"url" : "/"
} ],
"extensions" : {
"x-some-extension" : "some-value"
}
}
```
I would expect `x-some-extensions` to be directly under the root as it was in the initial `json` variable.
=> Json.pretty puts extensions in wrong place

modules/swagger-parser-core/src/main/java/io/swagger/parser/models/ParseOptions.java, modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/OpenAPIV3Parser.java, modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/resources/flatten.json
This PR contains:
New option in the parser: flatten.
It flattens the schemas in every object of an operation.
=> Flatten Schema Option

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
=> Fixing empty Definitions

modules/swagger-parser-v3/src/main/java/io/swagger/parser/v3/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/parser/v3/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/oas3.yaml.template
This PR solves the refs examples:
When the option ResolveFully is set to true, it will bring all the ref schemas and ref examples in components and will put them inline.
This is used in the inflector in order to mock the example responses when the controller is not implemented.
Solves #558
=> Resolve fully examples

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/empty-oas.yaml
A spec without components couldn't be resolved fully. Instead you got a NPE.
=> NPE in ResolverFully when components is missing

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/over-quoted-example.yaml
Removes the extra surrounding `"` around string examples.
I have found that swagger-codegen has a workaround for this, but I prefer fixing it right in the code here.
See https://github.com/swagger-api/swagger-codegen/pull/5778
=> Over quoted string example

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
=> fixing security requeriments

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/ParseOptions.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
Some users don't want to aggregate anyOf/allOf/oneOf schemas but simply wants all refs solved.
This solution adds a flag inside the `ResolverFully` and when schemas are processed It checks this flag. In case user don't want to aggregate, It generates a new list of subschemas solved and saves it to the composedSchema object.
I've also added a flag in `ParseOptions` that `OpenAPIV3Parser` reads during `readContents()` and I've wrote a test. For default the parser aggregate, as is now
=> Added flag to avoid aggregation of anyOf/allOf/oneOf schemas while using resolveFully()

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/oneof-anyof.yaml, modules/swagger-parser/src/test/resources/definitions.yaml, modules/swagger-parser/src/test/resources/spec.yaml
Fixes #584 came up while developing https://github.com/swagger-api/swagger-inflector/issues/215
=> Fix array schema deserialization

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/JsonToYamlFileDuplicator.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RefUtilsTest.java, modules/swagger-parser/src/test/resources/nested-references/b.yaml, modules/swagger-parser/src/test/resources/refs-name-conflict/a.yaml, modules/swagger-parser/src/test/resources/refs-name-conflict/b.yaml
Create new names by adding _{number} to new ref name if a conflict would occur.
=> $ref name conflicts for Swagger 2

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/refs-name-conflict/a.yaml, modules/swagger-parser-v3/src/test/resources/refs-name-conflict/b.yaml
Create new names by adding _{number} to new ref name if a conflict would occur.
=> $ref name conflicts for OAS 3

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/ref-without-component/a.yaml, modules/swagger-parser-v3/src/test/resources/ref-without-component/b.yaml
According to how i interpret the spec the "components" object is not required. I wish it were! (Or at least default to an empty components object) I have had so some bugs where I assume components exists...
According to the deserializer it assumes it is required. (The `true` means it is required) https://github.com/swagger-api/swagger-parser/blob/647bfe2c8cad362d837c052980939134933c70b2/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L137
This PR fixes a NPE in the resolver when the spec is missing the components tag and using external refs. I haven't checked, but I wouldn't be surprised if there are other cases of `openAPI.getComponents().getSomeSubObject()` assuming components is not null. Maybe thinking about defaulting the root components to …
=> Referring without components

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/additionalProperties.yaml, modules/swagger-parser/src/test/resources/globals.yaml
=> fixing bug resolving additionalProperties #342

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/additionalProperties.yaml, modules/swagger-parser-v3/src/test/resources/globals.yaml
fixing bug when parser trying to solve remote ref in additional properties schema issue #342
=> Schema with Additional properties was not solving remote refs #342

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/PathsProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
If a method had no parameters we got NPE when resolving
=> Avoid NPE when parameters only exist on path level

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/allOf-relative-file-references/models/fancy_pet.json, modules/swagger-parser/src/test/resources/allOf-relative-file-references/models/pet.json, modules/swagger-parser/src/test/resources/allOf-relative-file-references/parent.json
Fix for Issue #616
Issue #616 arises due to an unchecked use-case where one external file is referenced with respect to the `parent` instead of the `source` where the reference is made.
Similar use-cases are handled correctly elsewhere but missed out in the case of `ComposedModels`. This issue is specific to ComposedModel only i.e. `allOf`. 
The fix leverages existing `join` function to normalize and resolve the paths before sending it for processing the external definitions.
CC: @tzimisce012 based on previous commits in this area.
=> Fix for issue #616 allOf fails to resolve RELATIVE ref

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java
This PR fixes the issue #594  adding maxItems and minItems to the definitions method in the deserializer, when the Model in the body Parameter is ArrayModel.
=> adding maxItems and MinItems into ArrayModel deserializing - ticket#594

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/allOf-properties-ext-ref/models/pet.json, modules/swagger-parser/src/test/resources/allOf-properties-ext-ref/models/purebred_pet.json, modules/swagger-parser/src/test/resources/allOf-properties-ext-ref/models/swagger.json, modules/swagger-parser/src/test/resources/allOf-properties-ext-ref/swagger.json
Fix for issue #620 where `allOf` fails to process load properties with external `$ref`
sample: 
```
{
"allOf": [
{
"$ref": "./pet.json"
},
{
"type": "object",
"properties": {
"mother": {
"$ref": "./pet.json"
}
}
}
]
}
```
This PR fixes the issue where `pet.json` under `properties` fails to load.
=> Fix for #620: allOf fails to process load properties with external $ref

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/allOfAndRef.yaml
Fixing bug in resolve combinators, and adding test.
=> fix resolve combinators and test to fix PR#233

modules/swagger-parser-v2-converter/pom.xml, modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/booleanAdditionalProperties.json, pom.xml
refs swagger-api/swagger-core#2461
#499 and fixing refs in additionalProperties Resolving RefExternalResolver #342 (in v3)
=> Supporting change in additionalProperties Boolean and Schema

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/oas3.yaml.template
__v2.0.0-rc2__
When using __OpenAPIDeserializer__ to deserialize a PathItem with a `trace` operation, the said operation is null in the generated `OpenAPI` object.
OAS 3 definition:
```yaml
openapi: 3.0.0
servers:
- url: 'https://whatever.net/v1'
info:
description: ''
version: 1.0.0
title: Demo for cookie apiKey
paths:
/dummy:
trace:
description: Dummy operation to test retrieval of trace operations
responses:
200:
description: Dummy response
```
Test code:
```java
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.core.util.Yaml;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import io.swagger.v3.parser.util.OpenAPIDeserializer;
import org.testng.annotations.Test;
import java.nio.file.Path;
import …
```
=> :bug: Fix trace operations

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/oas3.yaml.template
__v2.0.0-rc2__
When using __OpenAPIDeserializer__ to deserialize security schemes with `type: apiKey` and `in: cookie`, the value of `in` is `null` in the generated `OpenAPI` object.
OAS 3 definition:
```yaml
openapi: 3.0.0
servers:
- url: 'https://whatever.net/v1'
info:
description: ''
version: 1.0.0
title: Demo for cookie apiKey
paths: {}
components:
securitySchemes:
API_KEY:
type: apiKey
description: The API key
name: auth
in: cookie
```
Test code:
```java
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.core.util.Yaml;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import org.testng.annotations.Test;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import static …
```
=> :bug: Fix in:cookie in apiKey security schemes

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java, modules/swagger-compat-spec-parser/src/test/java/io/swagger/parserExtensions/SwaggerCompatConverterTest.java
Swagger20Parser already can load input spec from classpath, but codegen project loads extensions one them is SwaggerCompatConverter and it fails loading from classpath
This fixes https://github.com/swagger-api/swagger-codegen/issues/2666
=> Fix to SwaggerCompatConverter so it can load inputSpec from classpath.

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/oneof_name_conflict/oneOf-external-ref-name-conflict.yaml, modules/swagger-parser-v3/src/test/resources/oneof_name_conflict/relative_ref/OtherPets.yaml
in oneOf ComposedSchema by default the propertyName field of the discriminator has value same as schema name. In case of name conflict the name of the schema changes, effectively changing the mapping. Fixed this case by keeping the older mapping.
Also in case of name conflict, the reference in the mapping was not changing.
=> Fix discriminator mapping If there are any name conflict for ComposedSchema (oneOf)

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTests.java, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-421-defns.yaml, modules/swagger-parser/src/test/resources/nested-file-references/common/issue-421-parms.yaml, modules/swagger-parser/src/test/resources/nested-file-references/issue-421.yaml
=> Fix handling of relative refs without leading dot

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/allOfRef.yaml, modules/swagger-parser-v3/src/test/resources/composedSchemaRef.yaml, modules/swagger-parser-v3/src/test/resources/refComponents.yaml
fixing allOf external resolving refs #628
=> fixing allOf external resolving refs #628

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/int64example.yaml
In int64example.yaml the example value comes out as -81224344 in an Integer. 
Maybe there is a better way of checking for int64 examples, but this seems to do the job at least. I'm happy to change if there is some obvious better way this should be done in. :)
=> Avoid overflow when storing an int64 in an Integer

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RefUtilsTest.java, modules/swagger-parser/src/test/resources/issue_643.yaml, modules/swagger-parser/src/test/resources/xyz.yaml, pom.xml
This PR fixes issue #643 and refactors #590 
It adds a number at the end of a reference definition to avoid duplicates, and adds it to the definitions map.
=>  Avoid duplicating definitions when they have the same name

modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java, pom.xml
Ref https://github.com/swagger-api/swagger-codegen/issues/6896
Depends upon https://github.com/swagger-api/swagger-core/pull/2508
=> Handle untyped schemas

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/LocalReferenceTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/NetworkReferenceTest.java
Failing tests in FileReferenceTest.
=> fixing failing tests in master

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/testPattern.yaml
=> fix pattern deserializer

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/resources/issue-705.yaml
=> Fix inlineResolver adding schema type.

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-758.json
Hi team,
This PR is to solve the issue 'OpenAPI v2 Converter: NPE when 'enum' field is available and 'type' field is missing in query parameter' as mentioned in #758 
Thanks,
Mohammed
=> Fix for issue 758

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-762.json
Hi team,
This PR is to fix the issue 'OpenAPI v2 Converter: NPE when type is array and 'items' field is missing in array property' [762](https://github.com/swagger-api/swagger-parser/issues/762).
Thanks,
Mohammed
=> Fix for issue 762

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ParameterProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/ParameterProcessorTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java, modules/swagger-parser/src/test/resources/issue749-main.yaml, modules/swagger-parser/src/test/resources/issue749-reference.yaml
Hi team,
This PR is to solve the issue '$ref in external file in parameter with resolve option true' as mentioned in https://github.com/swagger-api/swagger-parser/issues/749
Thanks,
Mohammed
=> Fix for 749

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/NetworkReferenceTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-742.json
Replacement for #754 with additional changes to fix issue #742
=> Convert Server with relative location to absolute url

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/extensions-responses.yaml
=> Extensions in Paths and Responses were not being parsed

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-765.yaml
Hi team,
This PR is to solve the issue #765 (requestBody not correctly populated when Parameters is a list of $refs (OAS 2 to 3 conversion))
Thanks,
Mohammed
=> Fix for issue 765

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-786.json
Hi team,
This PR is to solve the issue #786 (Open API V2 Converter: NPE when flow field is missing in securityDefinitions (OAS 2 to 3 conversion))
Thanks,
Mohammed
=> Fix for issue 786 (Open API V2 Converter: NPE when flow field is missing in securityDefinitions)

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java
Hi team,
This PR is to solve the issue #785  (OpenAPIParser.readLocation fails when fetching valid Swagger 2.0 resource with AuthorizationValues provided (OAS 2 to 3 conversion))
Thanks,
Mohammed
=> Fix for issue 785 (OpenAPIParser.readLocation fails when fetching valid Swagger 2.0 resource with AuthorizationValues provided)

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-745.yaml
Hi team,
This PR is to solve the issue #745 (OpenAPI Converter: Issue in converting server url in RFC 3986 format from OpenAPI Spec 2 to Open API Spec 3 (OAS 2 to 3 conversion))
Thanks,
Mohammed
=> Fix for issue 745 (Issue in converting server url in RFC 3986 format from OpenAPI Spec 2 to Open API Spec 3)

modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java, modules/swagger-compat-spec-parser/src/test/java/io/swagger/converter/LegacyConverterTest.java, modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/issue799.json
fixes for issue #799  returning ref as internal
=> fixes for issue #799 returning ref as internal

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/OperationProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/ResponseProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/OperationProcessorTest.java, modules/swagger-parser/src/test/resources/oapi-reference-test/components/referent.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test/components/response-with-reference.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test/components/schema-with-reference.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test/index.yaml, modules/swagger-parser/src/test/resources/relative-file-references/json/paths/healthPath.json, modules/swagger-parser/src/test/resources/relative-file-references/json/responses/errorResponses.json, modules/swagger-parser/src/test/resources/relative-file-references/yaml/paths/healthPath.yaml, modules/swagger-parser/src/test/resources/relative-file-references/yaml/responses/errorResponses.yaml
Fix issue #811 OAS2 - RefResponse -> RefSchema external Resolving
=> Fix issue #811 OAS2 - RefResponse -> RefSchema external Resolving

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue-834/components/response1.yaml, modules/swagger-parser/src/test/resources/issue-834/components/response2.yaml, modules/swagger-parser/src/test/resources/issue-834/components/schema.yaml, modules/swagger-parser/src/test/resources/issue-834/index.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test2/components/referent.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test2/components/schema-with-reference.yaml, modules/swagger-parser/src/test/resources/oapi-reference-test2/index.yaml
=> Fixes for issue #834 in OAS 2

modules/swagger-parser-v2-converter/pom.xml, modules/swagger-parser-v3/pom.xml, modules/swagger-parser/pom.xml
This PR fixes following Maven warnings:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.openapitools.swagger.parser:swagger-parser-v3:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.openapitools.swagger.parser:swagger-parser-v2-converter:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for …
```
=> Use ${project.parent.version} instead of ${parent.version}

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java, modules/swagger-parser/src/test/resources/reusableParametersWithExternalRef.json
Hi team,
This PR is to solve the issue #844 (parser not honoring redirect responses in open API 3.0) in open API Parser. 
Thanks,
Mohammed
=> Code roll-in for issue 844

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/ResolverCacheTest.java
This PR fixes a NullPointerException which occurs when an `ApiResponse` is read from an external reference which does not have any content defined.
=> Fix NullPointerException when resolving an ApiResponse with no content

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/linkIssue.yaml
Hi team,
This PR is to solve the issue #882 (RequestBody parameter is missing under links).
Thanks,
Mohammed
=> Fix for issue 882

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue_884.yaml
Hi team,
This PR is to solve the issue #884 (Links Internal Ref Not Resolved).
Thanks,
=> Fix for issue 884

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/internal-references-in-external-files/external.yaml, modules/swagger-parser-v3/src/test/resources/internal-references-in-external-files/main.yaml
This fixes issue #783 where internal references in elements originally located in external files were not properly updated once included in the main definition.
Also add a corresponding unit test (thanks to @Tiller for this, I used the unit test from his/her PR : #788 ).
=> Fix issue #783: update internal refs in external files

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java, modules/swagger-parser/src/test/resources/petstore.json
Motivation:
OpenAPI v2 supports setting default values for array parameters, but current v1 parser implementation fails to read such document as it always assumes the default value to be string.
Modification:
In case if parameter type is set to "array" then parse the default value as array.
Limitations:
The fix only allows parser to read such documents without errors while internally the default value is still represented as string. Changing that would require update of a much wider scope as it includes changes in both swagger-parser and swagger-models.
Fixes #387.
=> Fix for issue 387

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/duplicateOperationId.json
Hi team,
This PR is to solve the issue #258 (issue warning on duplicate operation ids) in swagger 1.0.40 version parser.
Thanks,
Mohammed
=> Fix for issue 258 (Code roll-in to Swagger 2.0)

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/simpleAllOf.yaml
I have gotten bit how resolveFully treats examples for allOf. Currently it makes an array of all the examples of the items in the allOf list. This will not generate a valid example in most cases.
**Given this spec:**
```
openapi: 3.0.0
info:
version: "1.0.0"
paths:
/foo:
get:
responses:
'200':
content:
application/json:
schema:
allOf:
- $ref: '#/components/schemas/FirstType'
- $ref: '#/components/schemas/SecondType'
/bar:
get:
responses:
'200':
content:
application/json:
schema:
allOf:
- $ref: '#/components/schemas/FirstType'
- $ref: '#/components/schemas/SecondType'
example:
someProperty: ABC
someOtherProperty: 42
components:
schemas:
FirstType:
type: object
properties:
someProperty:
type: string
example: abc
SecondType:
type: object
properties:
someOtherProperty:
type: integer
example: …
```
=> ResolveFully creates array example for allOf

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue-913/BO/Common/BasicComponents.json, modules/swagger-parser/src/test/resources/issue-913/BO/Resource/ApiSpecificationBO.json, modules/swagger-parser/src/test/resources/issue-913/BS/ApiSpecification.yaml
Please approve the fix for #913
=> Fix for #913 - problem with properties in object #ref

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/recursive.yaml, modules/swagger-parser-v3/src/test/resources/recursive2.yaml
fix for #914  and #929 
Added a Property Resolved Map to avoid infinite loops
=> Recurssion issue

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
Hi team,
This PR is to solve the issue #954 (Inconsistent handling of resolveFully and flatten options from ParseOptions)
Thanks,
=> Fix for issue 954

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/resources/simple.yaml
The property "name" is used in two places with different example values. They get the same example value after resolveFully.
Introduced in 2.0.6 and exists in 2.0.7 too.
=> Testcase showing a regression bug from #943.

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-983-domain.yaml, modules/swagger-parser-v3/src/test/resources/issue-983.yaml
External Schemas inside parameters were not being solved from external location
=> ref - #983 fixes remote reference parameter schemas in components

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-975/contract/openapi.yaml, modules/swagger-parser-v3/src/test/resources/issue-975/types/responses.yaml, modules/swagger-parser-v3/src/test/resources/issue-975/types/types.yaml
As stated in [Issue 975](https://github.com/swagger-api/swagger-parser/issues/975), the reference resolver for properties does not fully recurse. This can lead to unresolved references when parsing with `ParseOptions.setResolveFully(true)` and there are properties with nested arrays/maps/composed schemas. The included test case has 10 variants of properties, of which 7 were not resolved fully before the change.
Prior to the fix, these are the failed test cases:
```
[ERROR] Failures: 
[ERROR]   OpenAPIV3ParserTest.testIssue975_allOf:1744 expected [#/components/schemas/Image] but found [./types.yaml#/components/schemas/Image]
[ERROR]   OpenAPIV3ParserTest.testIssue975_anyOf:1737 expected [#/components/schemas/Image] but found [./types.yaml#/components/schemas/Image]
[ERROR] …
```
=> Fix for issue 975

modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue-995/digitalExp-CommonDefinitionDomain.yaml, modules/swagger-parser/src/test/resources/issue-995/digitalExp-Product-Unresolved.yaml
refs #995 - fixing discriminator with remote enum reference
=> refs #995 - fixing discriminator with remote enum reference

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1015.json
Fixed and Improved validation on default value according to schema type.
=> fix #1015 and test

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/RefUtilsTest.java, modules/swagger-parser-v3/src/test/resources/issue-1040/api.yaml, modules/swagger-parser-v3/src/test/resources/issue-1040/lib/lib.yaml
* Fix #1040 issue - duplicated reference path
=> #1040 Fixed duplication of external reference path

pom.xml
To prevent having SNAPSHOT versions in the dependency tree in released versions, I propose to add the `maven-enforcer-plugin` to the build with the `requireReleaseDeps` activated for release build.
Because this project is using SNAPSHOT versions during development, I think that using `onlyWhenRelease = true` is the appropriate setting for this project.
Documentation: https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html
Related:
* https://github.com/swagger-api/swagger-parser/issues/1053
* https://github.com/swagger-api/swagger-parser/pull/829#issuecomment-418793197
* https://github.com/swagger-api/swagger-parser/pull/1056 (same change for `master` branch)
=> Add maven-enforcer-plugin to prevent SNAPSHOT usage in releases (v1)

pom.xml
To prevent having SNAPSHOT versions in the dependency tree in released versions, I propose to add the `maven-enforcer-plugin` to the build with the `requireReleaseDeps` activated for release build.
Because this project is using SNAPSHOT versions during development, I think that using `onlyWhenRelease = true` is the appropriate setting for this project.
Documentation: https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html
Related:
* https://github.com/swagger-api/swagger-parser/issues/1053
* https://github.com/swagger-api/swagger-parser/pull/829#issuecomment-418793197
=> Add maven-enforcer-plugin to prevent SNAPSHOT usage in releases

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
**What is the problem:** When swagger-parser is used in an OSGi bundle, it fails to find extensions because it only looks into the current thread classloader. In an OSGi environment, swagger itself and its extensions (like v2 support) are not available from the tccl.
**What is the solution:** Load extensions from both tccl and the SwaggerParserExtension classloader
=> OpenAPIV3Parser#getExtensions() not finding extensions on OSGi #1003

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
=> Fix NullPointerException when schema is null

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1071.yaml
Fix parsing of MapSchema  refs #1071
=> Fix parsing of MapSchema 

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java, modules/swagger-parser/src/main/java/io/swagger/parser/OpenAPIParser.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
What is the problem: Following #1068 it appears the same getExtensions mechanism is also used by OpenAPIParser. The same fix should therefore be applied
What is the solution: Reuse getExtensions code from OpenAPIV3Parser
=> OpenAPIV3Parser#getExtensions() not finding extensions on OSGi #1003. Applying same fix to OpenAPIParser

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/issue-1090.yaml
Extract the `StringUtils.isBlank(schema.getType())` condition from the if introduced with #1076.
Fix for issue #1090.
=> Fix for issue #1090

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
**What is the problem:** In our unit tests,  properties need to appear in a specific order. We are having issues when these tests are run with different JDKs because HashMap ordering is not guaranteed.
**What is the solution:** Replace HashMap with LinkedHashMap in SwaggerConverter.java.
Please note that a unit test for this PR would be subject to the same JDK issue mentioned here, so no unit test is provided.
=> Properties order lost while converting from v2 to v3 #997

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1105/domain.yaml, modules/swagger-parser-v3/src/test/resources/issue-1105/swagger-api.yaml
Resolving Remote Ref Response with ArraySchema Ref Items
=> Resolving Remote Ref Response with ArraySchema Ref Items  issue #1105

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
The xml information was ignored while creation of array models... So I added them. 
This is e.g. relevant when using openapi-generator (3.3.4 in my case) to generate custom java classes from swagger2.0 descriptions with correct xml annotations.
=> xml information in array models

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue-111.yaml
This is the fix for the issue #1047 for the version 1 of swagger
=> fix for issue #1047 v1

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-1113.yaml
Fixes issue #1113. We no longer prepend `//` to the `basePath` when the `basePath` already begins with a `/`. Fixes (and contains) the failing test added in #1114.
=> Avoid prepending forward slashes to URLs when the URL already starts with a forward slash

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/PathUtils.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/PathUtilTest.java
PathUtils - improve url lookup to find classpath resources not in swagger-parser jars. 
ResolverCache, RefUtils - add lookup by classpath when file path not resolvable.
=> issue-1133 - Parser does not resolve $ref pointing to relative locations on classpath

modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/ParseOptions.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/resources/skipMatches.yaml
Background and reasoning in swagger-api#1158.
=> swagger-api#1158: Provide the ability to toggle the match skipping for inline model resolving

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue1169.yaml
=> Fix for multiple path params in a same URI segment of a path

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-1164.yaml
Resolves #1164 
Motivation:
`PrimitiveType` contains a full mapping (and constructors!) for built-in tracked schema subtypes. By using this, the Schemas generated by the 2to3 converter will have a similar shape to the native 3.x schemas, permitting more unified structure handling for clients (permitting relying on `isInstanceOf` exclusively, instead of `isInstanceOf` as well as `getType() == "xyz"`)
Delegating to `fromTypeAndFormat` to get a particular instance, then `createProperty()` to instantiate the particular schema resolves the issue I was running into.
If we can't actually look up the mapping, fall back to the original behaviour.
=> Using specialized schema subclasses

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue1190/issue1190.yaml
refs - issue #1190 - fix  ArraySchema with additionalProperties deserializing.
=> refs - issue #1190 - fix  ArraySchema with additionalProperties

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java, modules/swagger-parser/src/test/resources/issue1204.yaml
refs - issue #1204 
Reading the spec for 2.0 swagger version, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#contact-object has the vendor extension as valid.
The fix was made in  https://github.com/swagger-api/swagger-core/pull/3320, which need to be reviewed and merged before this PR.
=> Fixing Contact Object vendor Extension was not parsed

modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/FileReferenceTest.java, modules/swagger-parser/src/test/resources/nested-file-references/common/eventsWithPagingInSubdir.yaml, modules/swagger-parser/src/test/resources/nested-file-references/common/paging2.yaml, modules/swagger-parser/src/test/resources/nested-file-references/issue-1223.yaml
=> issue1223 fix nested dir ref for path

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue1143.json
refs - issue #1143 - changes to support properties in ComposedModel
depends on https://github.com/swagger-api/swagger-core/pull/3342
=> refs - issue #1143 - changes to support properties in ComposedModel

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ExternalRefProcessorTest.java
e.g. properties of Contact model is empty.
Contact:
type: object
discriminator: jsi_type
properties: {}
ContactEmail:
allOf:
- $ref: '#/definitions/Contact'
- type: object
required:
- emailAddress
properties:
emailAddress:
type: string
=> fixed a NPE occurred during processing discriminator in an empty model,

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
Issue: https://github.com/swagger-api/swagger-parser/issues/1273
=> Fix duplicate '.responses' in location string.

.gitignore, modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/parameters-external/data-plane/Common/Parameters.json, modules/swagger-parser/src/test/resources/parameters-external/data-plane/ComputerVision/stable/v1.0/ComputerVision.json, modules/swagger-parser/src/test/resources/parameters-external/readme.txt, modules/swagger-parser/src/test/resources/parameters-external/simple/externals-level-0.json, modules/swagger-parser/src/test/resources/parameters-external/simple/externals-level-1.json, modules/swagger-parser/src/test/resources/parameters-external/simple/externals-level-2.json
Issue 1299 external parameters broken in Swagger parser 1.0.49 for Swagger 2.0 specs.
See `io.swagger.parser.SwaggerParserTest.testExternalParameters()`
=> Issue 1299 Swagger 2.0 external parameters broken

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
Because in the v1 library operation.getSecurity() doesn't return a list of SecurityRequirements cfr the top-level security field in the swagger file, I opted for adding an empty Map to the list to represent the none security requirement.
We need swagger-parser to retain the unsecured security requirement on an operation level. Now it is stripped
=> #1305 fixing parsing of empty securityRequirement

modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java
Some test cases in OpenAPIV3ParserTest to not have the `@Test` annotation. They are not executed during the maven build.
This PR fixes this.
=> Add missing @Test annotations in OpenAPIV3ParserTest

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ObjectMapperFactory.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/duplicateHttpStatusCodes.yaml, modules/swagger-parser-v3/src/test/resources/oas3.yaml.template, modules/swagger-parser-v3/src/test/resources/petstore.yaml
This PR is doing the same change as @sullis did in #1271 for JSON but for the YAML format.
Without the `STRICT_DUPLICATE_DETECTION`, when there are duplicates keys Jackson is silently ignoring the first one. This results in unpredictable behavior.
Following Yaml is invalid because of the 2 `"200"` keys in the response map:
```yaml
openapi: 3.0.1
info:
title: title
description: This is a sample server
license:
name: Apache-2.0
url: http://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.0
servers:
- url: https://api.absolute.org/v2
description: An absolute path
paths:
/whatever:
get:
summary: Some operation
description: Some operation
operationId: doWhatever
responses:
"200":
description: OK
"200":
description: duplicate HTTP status code
```
As comparison the Swagger-Editor Javascript …
=> enable STRICT_DUPLICATE_DETECTION in Jackson parser for Yaml

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/Issue1316.yaml
fix for issue #1316
ContentType in Encoding Object should not be required.
=> fix for issue #1316: ContentType in Encoding Object should not be required.

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/domain-issue-1335.yaml, modules/swagger-parser-v3/src/test/resources/issue1335.yaml
Fix for issue #1335 -  OAS3: Resolved YAML doesn't include Example components from domains
=> fix for issue #1335 - OAS3: Resolved YAML doesn't include Example components from domains

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java, modules/swagger-parser-v3/src/test/resources/blankQueryParameter.yaml, modules/swagger-parser-v3/src/test/resources/emptyQueryParameter.yaml
Empty and blank query parameter examples were parsed to null.
Now they are parsed to an empty and blank string respectively.
Fixes #1375
=> Fix for issue #1375

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/resources/flattenArrayItems.yaml
Flatten ComposedSchemas at Array Items in responses, parameters, requestBodies.
refs issue #1382
=> Flatten ComposedSchemas at Array items in responses, parameters, requestBodies 

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java, modules/swagger-parser-v3/src/test/resources/additionalPropertiesFlatten.yaml, modules/swagger-parser-v3/src/test/resources/flattenArrayItems.yaml
=> Fix for Flatten Map Schema when Inline ComposedSchema

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1367.yaml
Fix and test for Parser cannot process 'allOf' correctly - issue #1367.
Changed in the ResolveFully Class, added the enum to the resolved final schema.
=> Fix and test for Parser cannot process 'allOf' correctly - issue #1367

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java
This is a proposed change to retain the original value of the "swagger" keyword when converting a OAS/Swagger 2.0 document to a 3.0 OAS document.
=> Add extension to keep track of original swagger version

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java
fix NPE when URL matcher is null in Remote Url
=> fix NPE when URL matcher is null in Remote Url

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/RelativeReferenceTest.java
fix for issue invalid remote server url.
=> fix for issue invalid remote server url

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
Fixes https://github.com/swagger-api/swagger-parser/issues/1402
=> Issue 1402: Fix NPE when a path references an undeclared path parameter.

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
This fixes the NPE (see issue #1409) and also alters the resulting error message to more accurately describe the problem.
=> When parameter style is invalid, return a helpful message instead of throwing an NPE

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java, modules/swagger-parser-v3/src/test/resources/relativeTest.yaml
When loading API definitions from a URL, the parser only handles 301 redirects
https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RemoteUrl.java#L153
and cannot handle other 3xx redirects - 302, 303, etc.
=> adding redirect response codes to remote url

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java
This pull request fixes handling of `multipleOf` between 0 and 1, as specified in #1457. I've also added a test case for this specific scenario.
The existing code would call `intValue()`, which involves rounding. When that would happen, low values would round to 0, failing the ensuing test.
P.S.: Getting to the `else` branch trigger a `NullPointerException` because `result` is `null`. I haven't tried to fix that issue as I believe it would be a completely different beast.
=> Handle multipleOf between 0 and 1

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/allOf-example/allOf.yaml
Required properties are not properly read from a composed schema, for example, in this example:
```yaml
definitions:
User:
type: object
required:
- email
properties:
email:
type: string
UserRegister:
allOf:
- $ref: '#/definitions/User'
type: object
required:
- password
properties:
password:
type: string
```
the required property `password` is not found when i call:
```java
final Model model = swagger.getDefinitions().get("UserRegister");
final ComposedModel composedModel = (ComposedModel) model;
composedModel.getRequired(); // empty or null
```
This issue is affecting `swagger-codegen` reported at https://github.com/swagger-api/swagger-codegen/issues/7058
=> read required elements in composed models.

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
=> OpenAPIDeserializer: If "examples" and "example" both defined, ignore "example" with a warning

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/InlineModelResolver.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/ParseOptions.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/InlineModelResolverTest.java, modules/swagger-parser/src/test/resources/flatten.json
This change allows allow swagger-parser consumers who are using OpenAPI 2.0 APIs to flatten definition models in the returned spec similar to OpenAPI 3.0 API can be flatten when using swagger-parser 2.x
* Implementation of InlineModelResolver.java and InlineModelResolverTest.java are taken directly from swagger-codegen project. Only modifications are to the package name. This was intentional so all behaviour is consistent.
* Added two additional interfaces in SwaggerParser.java for reading the input spec; these take a `ParseOptions` object - this is based on the interface used in swagger-parser 2.x
=> feat: Add Inline Resolver to OpenAPI 2.0 parser

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/refs-name-conflict/a.yaml, modules/swagger-parser-v3/src/test/resources/refs-name-conflict/c.yaml
Calculation of schema name in external ref processor takes into account that more than 2 schemas may have the same name.
The counting of schemas starts from `1` instead of `2`.
Note: the warn level of the logger in line 62 seemed too high for a normal operation so I lowered it. Let me know if you think it was `warn` for an abnormal operation.
Closes #1501
=> Fix issue #1501: External schema name is correctly constructed

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ResolverCache.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/same-refs-different-model-domain.yaml, modules/swagger-parser-v3/src/test/resources/same-refs-different-model-valid.yaml, modules/swagger-parser-v3/src/test/resources/same-refs-different-model.yaml
I'm facing `java.lang.ClassCastException` when my specification has two similar $refs for different models. When $refs point to components from the same specification everything works fine.
`
java.lang.ClassCastException: Cannot cast io.swagger.v3.oas.models.parameters.HeaderParameter to io.swagger.v3.oas.models.headers.Header
at java.base/java.lang.Class.cast(Class.java:3816)
at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:110)
at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalHeader(ExternalRefProcessor.java:455)
at io.swagger.v3.parser.processors.HeaderProcessor.processHeader(HeaderProcessor.java:42)
at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:66)
at …
=> #SWOS-242: test cases for ClassCastException when resolving external refs

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/domain.yaml, modules/swagger-parser-v3/src/test/resources/issue251.yaml
Fix issue 251 - broken domain resolving
=> fix issue 251 - broken domain resolving

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/InlineModelResolverTest.java
Signed-off-by: Cristiano V. Gavião <cvgaviao@gmail.com>
=> fix issue #1527

modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/issue-1541/main.yaml
schemas an of inline responses are parsed different from ones in definitions.
This manifests it's self as a bug in the generator: https://github.com/OpenAPITools/openapi-generator/issues/9086 where `additionalProperties` behaves differently if it's in a response in-line or in definitions.
=> fix schemas parse inconsistencies

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1543/openapi.yaml, modules/swagger-parser-v3/src/test/resources/issue-1543/schemas/PingResponse.yaml, modules/swagger-parser-v3/src/test/resources/issue-1543/schemas/_index.yaml
Fixes #1543
... subtring(0, indexOf ... causes StringIndexOutOfBounds if the char searched for is missing. This meant that refs like $ref("another_file.json#/thing") could not be parsed. In addition, File.sparatorChar was used to find separators in directory part of ref, causing most every parsing attempt to fail on windows. We should probably require "/" to be used as path separator.
=> external $ref without / caused exception

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
In case $ref refers to path with parameter, using whole $ref in processRefSchema as externalFile argument results in URISyntaxException
java.net.URISyntaxException: Illegal character in fragment at index 49: ../v1/checkout.yml#/paths/~1checkout~1orderItem~1{orderItemId}
at java.base/java.net.URI$Parser.fail(URI.java:2915)
at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
at java.base/java.net.URI$Parser.parse(URI.java:3130)
at java.base/java.net.URI.<init>(URI.java:600)
at io.swagger.v3.parser.processors.ExternalRefProcessor.join(ExternalRefProcessor.java:977)
at io.swagger.v3.parser.processors.ExternalRefProcessor.constructRef(ExternalRefProcessor.java:928)
at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefSchema(ExternalRefProcessor.java:918)
at …
=> Fix URISyntaxException for $ref to path with param

modules/swagger-parser/pom.xml
Backport of https://github.com/swagger-api/swagger-parser/pull/1251 to the v1 branch
This change would be great to have in a 1.0.55 release :)
=> Remove unused slf4j dependencies from pom

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java, modules/swagger-parser/src/test/resources/exampleSpecs/specs/issue1553.yaml
When parsing API specs with relative server URLs when the path to the spec is specified with Windows directory separators (\) instead of UNIX (/), swagger-parser fails to generate OpenAPI object with no error message.
This is the cause of #1553 and most likely of https://github.com/OpenAPITools/openapi-generator/issues/8266 as well
=> #1553 fails to generate spec on relative server urls on Windows

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java
Fix tests :
- OpenAPIV3ParserTest.testLoadExternalNestedDefinitions,
- OpenAPIV3ParserTest.testLoadExternalNestedDefinitionsWithReferenceWithinSameFolder
- OpenAPIV3ParserTest.testRelativePathIssue1543
Not fix tests :
- OpenAPIV3ParserTest.testLoadExternalNestedDefinitionsWithReferenceOnDifferentFolderLevels
- OpenAPIV3ParserTest.testLoadExternalNestedDefinitionsWithReferenceWithinSubfolder
=> fix 1511 for windows build

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue203/issue203AllOf.yaml
fix xml attribute in resolveFully option in ComposedSchema
=> fix xml attribute in resolveFully option in ComposedSchema

pom.xml
This PR does the following:
* #1586
=> Issue #1586: Update commons-io from 2.6 to 2.11.0

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
There is a difference between `"null"` and `null` in both JSON and YAML. Currently this difference is ignored and all null values are parsed as the string `"null"` when a schema `type` is set to `string`.
=> Allow null string values

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java, modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RemoteUrlTest.java
allow to filter authorization by URL
depends on https://github.com/swagger-api/swagger-core/pull/3995
=> allow to filter authorization by URL

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java, modules/swagger-parser/src/test/resources/issue-1621/example.get.yaml, modules/swagger-parser/src/test/resources/issue-1621/example.openapi.yaml, modules/swagger-parser/src/test/resources/issue-1621/example.post.yaml
Hi team,
This PR is to solve issue #1621  (OpenAPIParser is resolving the wrong schema for an operation)
This issue happens when the referenced file name contains more than 1 dot.
Thanks,
=> Fix for issue-1621

pom.xml
Signed-off-by: Pratim S Chaudhuri [pratim.sunilkumar.chaudhuri@mercer.com](mailto:pratim.sunilkumar.chaudhuri@mercer.com)
This fix includes changes to mitigate CVE reported at - https://github.com/FasterXML/jackson-databind/issues/3328
=> Update Jackson to include CVE fixed in version 2.12.6

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OAI31DeserializationTest.java, modules/swagger-parser-v3/src/test/resources/3.1.0/petstore-3.1_more.yaml
Adding missing keys to OAS 3.1 set in parser deserializer, to avoid them being add as extensions.
=> Adding missing keys to OAS 3.1 set

modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java
This issue references #1685 
It addresses the way parser deserializes the previous versions and returns the validation messages in the process for and edge case.
=> Add messages at SwaggerDeserializationResult if definition is malformed

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue1758.yaml
Fix and test for issue #1758.
Adds a validation message for parameters and headers when ref field in **internal references** are not being pointed at the right components tag.
=> fix and test for issue 1758

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-1767.yaml
Set `security` property of operation to an empty list if that's the case in the parsed file.
Resolves #1767
=> fix for issue 1767 - OpenAPI v2 converter

modules/swagger-parser-cli/pom.xml, modules/swagger-parser-cli/src/main/java/io/swagger/v3/parser/SwaggerParser.java, modules/swagger-parser-cli/src/test/java/SwaggerParserCLITest.java, modules/swagger-parser-cli/src/test/resources/fileWithNoErrorMessages.yaml, modules/swagger-parser-cli/src/test/resources/fileWithValidationErrorMessages.yaml, pom.xml
This is the initial work of the Github actions validate option.
=> initial Swagger Parser CLI

pom.xml
The package org.yaml:snakeyaml from 0 and before 1.31 are vulnerable to Denial of Service (DoS) due missing to nested depth limitation for collections.
=> CVE-2022-25857/CVE-2022-38752: bump snake-yaml dependency to avoid versions with public CVEs

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/reference/ReferenceUtils.java
Occurs on windows filesystems:
when absoluteUri is something like "C:/openapi.yml", the "scheme" part in URI object is resolved into "C". So it passes through all the statements and lands on an exception being thrown. A more resilient approach is to always default to reading from file when the scheme cannot be determined
=> Update ReferenceUtils to better support windows filesystem

modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java, modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v2-converter/src/test/resources/issue-1796.yaml
Fixes #1796 
Make sure the `required` field don't get lost when it is having an `allOf` in Swagger and you want to convert it to OpenAPI
=> Keep required field when converting composed model to OpenAPI

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/DeserializationUtils.java
With this patch, a user may set the system property 'maxYamlCodePoints' in order to override the default 3MiB limit configured in the org.yaml.snakeyaml package by default. This limit was implemented to prevent certain Denial-of-Service (DOS) attacks, but users should be given the opportunity to override this value for valid configurations which exceed the limit, such as the Redfish OpenAPI specification (developed by DMTF), which weighs in at 4.9MiB.
This patch was tested to work with openapi-generator-cli v6.3.0.
This PR closes #1871 
Signed-off-by: Ethan D. Twardy <ethan.twardy@gmail.com>
=> Allow user to override the Code Point Limit required by SnakeYaml

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/resolverIssue/Beta-1-swagger.yaml, modules/swagger-parser-v3/src/test/resources/resolverIssue/DOCUMENTATION_DOMAIN-3.0.0-domain.yaml
fix for issue when dereferencing OneOf which has references in it.
=> fix for issue when dereferencing OneOf

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
Currently, swagger-parser will error with the following message `attribute info.license.identifier is missing` when parsing an OpenApi 3.1 document where `license.url` and `license.name` is set (see the example document below).
According to the official OpenApi 3.1 schema it must have either the `license.url` or the `license.identifier` set but not both.
This PR will fix swagger-parser to work according to the schema.
Example OpenApi 3.1 which currently fails:
```yaml
openapi: 3.1.0
servers:
- url: 'http://abc:5555/mypath'
info:
version: '1.0'
title: dd
license:
name: test
url: http://example.com
paths:
/resource1/Id:
post:
description: ''
operationId: postOp
responses:
'200':
description: Successful
'401':
description: Access Denied
requestBody:
content:
application/json:
schema:
$ref: …
```
=> url and identifier in the license field are handled incorrectly

modules/swagger-parser-v2-converter/pom.xml
Hi, I am a user of project **_io.swagger.parser.v3:swagger-parser-v2-converter:2.0.27-SNAPSHOT_**. I found that its pom file introduced **_53_** dependencies. However, among them, **_7_** libraries (**_13%_**) have not been used by your project (the redundant dependencies are listed below). Reduce these useless dependencies can help prevent conflicts between library versions. MeanWhile, it can minimize the total added size to projects. It can also help enable advanced scenarios for this project. 
This PR helps **_io.swagger.parser.v3:swagger-parser-v2-converter:2.0.27-SNAPSHOT_** lose weight :) I have tested the revised configuration in my local environment. It is safe to remove the unused libraries.
Best regards
=> Could io.swagger.parser.v3:swagger-parser-v2-converter:2.0.27-SNAPSHOT drop off redundant dependencies to loose weight?

modules/swagger-parser-safe-url-resolver/README.md
This PR adds documentation to the swagger-parser-safe-url-resolver based on the info laid out in #1910
=> Add documentation for swagger-parser-safe-url-resolver

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/DeserializationUtils.java
This PR adds the possibility to set a custom YAML mapper for parsing OAS 3.0/3.1 documents with DeserializationUtils methods.
=> parser-v3: Extend DeserializationUtils to enable providing a custom YAML Mapper

modules/swagger-parser/src/main/java/io/swagger/parser/util/DeserializationUtils.java
This PR adds the possibility to set a custom YAML mapper for parsing OAS 2.0 documents with DeserializationUtils methods.
=> parser-v2: Extend DeserializationUtils methods to enable providing a custom YAMLMapper

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ClasspathHelper.java
This commit adds a fallback to `Thread.currentThread().getContextClassLoader().getResourceAsStream(file)` in the `ClasspathHelper` class.
Previously, if the `ClasspathHelper.class.getResourceAsStream(file)` and `ClassLoader.getSystemResourceAsStream(file)` methods returned `null`, no further attempts were made to load the resource, which caused issues in Quarkus applications in dev mode.
This commit adds an additional fallback to `Thread.currentThread().getContextClassLoader().getResourceAsStream(file)` to improve compatibility with the Quarkus class loading model.
Related Issue: #1968
=> Add fallback to Thread Context Class Loader for resource loading

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/PathsProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/PathsProcessorTest.java, modules/swagger-parser-v3/src/test/resources/issue-1955/merged_spec12.yaml, modules/swagger-parser-v3/src/test/resources/issue-1955/spec1.yaml, modules/swagger-parser-v3/src/test/resources/issue-1955/spec2.yaml, pom.xml
Fix for https://github.com/swagger-api/swagger-parser/issues/1955
It also fixes https://github.com/swagger-api/swagger-parser/issues/1918
=> Bugfix 1955 Schema refs of array parameters are not resolved for renamed schema components

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OAI31DeserializationTest.java, modules/swagger-parser-v3/src/test/resources/3.1.0/issue-1975.yaml
Changes const type from String to Object
Per json schema docs, const stores one values of any json schema type
- [json schema spec const definition](https://json-schema.org/draft/2020-12/json-schema-validation#name-const)
- [understanding const docs](https://json-schema.org/understanding-json-schema/reference/const)
- real world examples of const values in the json schema test suite, the schema value stored in the `"schema"` key: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/tests/draft2020-12/const.json#L6
Verification:
- java tests added verifying ingestion of json null/string/number/object/array/boolean
If merged, this will close out these issues:
- https://github.com/swagger-api/swagger-parser/issues/1975
- …
=> Fixes issue 1975: bug in const processing, const values of all types now processable

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java
This PR provides a cache mechanism that stores the extensions loaded per classloader.
Due to the caching mechanism the performance for loading the extensions (jsonSchemaParserExtensions) is improved.
This PR closes #1909
=> feat: introduce cache loaded extensions in OpenAPIDeserializer

modules/swagger-parser-safe-url-resolver/README.md, modules/swagger-parser-safe-url-resolver/pom.xml, modules/swagger-parser-safe-url-resolver/src/main/java/io/swagger/v3/parser/urlresolver/PermittedUrlsChecker.java, modules/swagger-parser-safe-url-resolver/src/main/java/io/swagger/v3/parser/urlresolver/exceptions/HostDeniedException.java, modules/swagger-parser-safe-url-resolver/src/main/java/io/swagger/v3/parser/urlresolver/matchers/UrlPatternMatcher.java, modules/swagger-parser-safe-url-resolver/src/main/java/io/swagger/v3/parser/urlresolver/models/ResolvedUrl.java, modules/swagger-parser-safe-url-resolver/src/main/java/io/swagger/v3/parser/urlresolver/utils/NetUtils.java, modules/swagger-parser-safe-url-resolver/src/test/java/io/swagger/v3/parser/urlresolver/PermittedUrlsCheckerTest.java, modules/swagger-parser-safe-url-resolver/src/test/java/io/swagger/v3/parser/urlresolver/matchers/UrlPatternMatcherTest.java, modules/swagger-parser-safe-url-resolver/src/test/java/io/swagger/v3/parser/urlresolver/utils/NetUtilsTest.java, modules/swagger-parser/pom.xml, modules/swagger-parser/src/main/java/io/swagger/parser/ResolverCache.java, modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java, modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerResolver.java, modules/swagger-parser/src/main/java/io/swagger/parser/util/ParseOptions.java, modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerParserTest.java, modules/swagger-parser/src/test/resources/safelyResolve/oas20SafeUrlResolvingWithLocalhost.yaml, modules/swagger-parser/src/test/resources/safelyResolve/oas20SafeUrlResolvingWithPetstore.yaml, pom.xml
Addresses: https://github.com/swagger-api/swagger-parser/issues/2030
This PR makes swagger-parser to utilizes safeUrlResolver when resolving OpenAPI 2.0 definitions.
The reason behind this change is described deeply under the following PR:
https://github.com/swagger-api/swagger-parser/pull/1910
The $refs are checked in ResolverCache class, in loadRef method.
In order to keep the backward compatibility, I've created a new constructor of ResolverCache so it is possible to explicitly pass the parseOptions through the SwaggerResolver.
=> SWG-9288 utilizing safe url resolver for OAS 2.0

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/SchemaProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/InlineModelResolver.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIResolverTest.java
Issue: https://github.com/swagger-api/swagger-parser/issues/2048
PR: https://github.com/swagger-api/swagger-parser/pull/2049
```
Caused by: java.lang.NullPointerException: Cannot invoke
"io.swagger.v3.oas.models.media.Schema.get$ref()" because "items" is
null
at io.swagger.v3.parser.processors.SchemaProcessor.processArraySchema(SchemaProcessor.java:218)
at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:69)
at io.swagger.v3.parser.processors.SchemaProcessor.processPropertySchema(SchemaProcessor.java:139)
at io.swagger.v3.parser.processors.SchemaProcessor.processSchemaType(SchemaProcessor.java:76)
at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:61)
at io.swagger.v3.parser.processors.ComponentsProcessor.processSchem …
```
=> [Issue 2048] NullPointerException in SchemaProcessor.processArraySchema()

modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java
Issue: https://github.com/swagger-api/swagger-parser/issues/2046
PR: https://github.com/swagger-api/swagger-parser/pull/2047
```
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "io.swagger.v3.parser.core.models.SwaggerParseResult.getMessages()" is null
at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:125)
at ...
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
The test is convoluted because the real test would be in the main parser module plus a dependency on this module, which one cannot do due to circularity, but, note that the NPE and fix are "real" and have been tested in production on my end.
=> [Issue 2046] NPE in OpenAPIV3Parser.read(String, List<AuthorizationValue>, ParseOptions)

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/ObjectMapperFactory.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/ObjectMapperTest.java
Relates to https://github.com/swagger-api/swagger-parser/issues/1524 - also consistent with swagger-core ObjectMapperFactory that adds JavaTimeModule by default.
=> add JavaTimeModule to Jackson ObjectMapper

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/PathsProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-2037/openapi.yaml, modules/swagger-parser-v3/src/test/resources/issue-2037/paths/get.yaml
This PR is to fix the issue ref #2037
=> Fix issue #2037

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/resources/issue-1886/components.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/openapi.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/array-types-ids.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/array-types.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/map-types-ids.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/map-types.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/set-types-ids.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/set-types.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/simple-types-ids.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/paths/simple-types.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/additional-properties.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/array-pojo.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/enum1.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/locale-translation-item.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/map-pojo.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/set-pojo.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/simple-pojo.yaml, modules/swagger-parser-v3/src/test/resources/issue-1886/schemas/translation-item.yaml
This PR is to fix https://github.com/swagger-api/swagger-parser/issues/1886
When parsing openapi definitions the results are different on Linux and Windows systems. It has been documented with the test: OpenAPIV3ParserTest#testIssue1886.
On Linux OS the schemas (with and without the fix) are resolved to:
ArrayPojo, Enum1, Enum1_1, Enum2, Enum3, MapPojo, SetPojo, SimplePojo, TransactionsPatchRequestBody, additional-properties, array-pojo, locale-translation-item, map-pojo, set-pojo, simple-pojo, translation-item
On Windows OS, without this fix, schemas are resolved to following names:
ArrayPojo, Enum1, Enum2, Enum3, MapPojo, SetPojo, SimplePojo, TransactionsPatchRequestBody, schemas\array-pojo, schemas\enum1, schemas\map-pojo, schemas\set-pojo, schemas\simple-pojo
=> Issue 1886

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/NetworkReferenceTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserTest.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/util/OpenAPIDeserializerTest.java
This is a valid API key definition.
```yaml
components:
securitySchemes:
ApiKeyAuth:        # arbitrary name for the security scheme
type: apiKey
in: header       # can be "header", "query" or "cookie"
name: X-API-KEY  # name of the header, query parameter or cookie
```
There already is validation that checks the `in` attribute is present. The purpose of this PR is to validate that the attribute value is one of "header", "query", or "cookie".
[Swagger docs](https://swagger.io/docs/specification/authentication/api-keys/) for reference.
=> Validate the api key 'in' attribute is cookie header or query.

modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java, modules/swagger-parser/src/test/java/io/swagger/parser/util/RefUtilsTest.java
Use `ExternalRefProcessor` for `RefUtils#buildUrl` to avoid `ArrayOutOfBoundsException`
Fix #750
=> Fix #750 by reusing ExternalRefProcessor

modules/swagger-parser/src/main/java/io/swagger/parser/processors/ModelProcessor.java, modules/swagger-parser/src/test/java/io/swagger/parser/processors/ModelProcessorTest.java
=> Test and fix #2083 properties in ComposedModel

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/processors/ExternalRefProcessorTest.java, modules/swagger-parser-v3/src/test/resources/issue-2104/depth1/depth2/definitions.yaml, modules/swagger-parser-v3/src/test/resources/issue-2104/depth1/depth2/product/definitions.yaml, modules/swagger-parser-v3/src/test/resources/issue-2104/openapi.yaml
=> fix(#2104): properly process inline refs in composed schemas

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3ParserDynamicRefTest.java, modules/swagger-parser-v3/src/test/resources/dynamicRef/dynamicref-example.yaml, modules/swagger-parser/pom.xml, modules/swagger-parser/src/test/java/io/swagger/parser/OpenAPIParserTest.java, modules/swagger-parser/src/test/resources/dynamicRef/dynamicref-example.yaml, pom.xml
NOTE: this PR requires swagger-core 2.2.32 to be released first
=> Add $dynamicRef

modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ExternalRefProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/ParameterProcessor.java, modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/processors/PathsProcessor.java, modules/swagger-parser-v3/src/test/java/io/swagger/v3/parser/test/OpenAPIV3RefTest.java, modules/swagger-parser-v3/src/test/resources/resolve-dot-containing-ref/externalRefDomain.yaml, modules/swagger-parser-v3/src/test/resources/resolve-dot-containing-ref/externalRefSpec.yaml, modules/swagger-parser-v3/src/test/resources/resolve-dot-containing-ref/standaloneSpec.yaml, pom.xml
=> fix $ref parsing when it contains dot inside component name
